### ISSUE TITLE
readNWISuv siteNumbers only accepts usgs 8-digit USGS site IDs?

### ISSUE THREAD

**Issue by mccreigh** [USGS-R/dataRetrieval#100]
Hi there-

First of all, this tool is fantastic. Thank you for making it. 

The discovery aspect of this tool is great and critical to my work. But I'm a bit confused about the output of this kind of command `meta <- whatWQPsites(huc='10190005')`, which gives me `meta$MonitoringLocationIdentifier` like this
```
...
[565] "NARS_WQX-FW08CO004" ...
[583] "USGS-06725100"      ...
[613] "USGS-395528105133800" ...
```

in relationship to  use of `readNWISSuv`. Can I only supply the numeric part of the MonitoringLoactionIdentifiers for rows/sites with identifiers like row 583 as the siteNumbers argument? The documentation is not specific ( `siteNumbers character USGS site number (or multiple sites). This is usually an 8 digit number` ) other than possibly limiting the query to USGS data. But the queries using other identifiers, even the longer USGS ones, have failed for me. In other words, am I only able to get a small subset of the data listed in meta with `readNWISSuv` and is there a way to get the other data listed in meta? Maybe I'm missing something.

Also, by the way, is there any access to gages-II data/attributes via these NWIS queries?

Thanks again, 
james

**Comment by ldecicco-USGS** [comment]
Only USGS sites can be accessed with `readNWISuv` (NWIS = USGS, WQP = USGS + others...ie NARS_WQX). Any number of digits in the siteNumbers argument are possible (so, both row 583 and 613 are possible). 

But, there's no guarantee that a site that collected water samples (that reported data to WQP) will have unit data (sensors). Some do, some don't. You can do a query to find out if the site has uv data:

```r
site <- c("USGS-395528105133800","USGS-06725100")
siteNWIS <- sapply(strsplit(site,"-"), function(x) x[2])
availableData <- whatNWISdata(siteNWIS, service = "uv")

Warning messages:
1: All formats failed to parse. No formats found. 
2: All formats failed to parse. No formats found
```

If you take the `service="uv"` off of the `whatNWISdata` request, you'll find out that both of those sites only measure "qw" "sv" "dv" data (water quality, sites visits, and daily values) - so nothing is returned from `readNWISuv`.

Re-reading your question, maybe you used the wrong 'meta' function? If you just want to find what sites have unit (sensor) data (data which would be returned from `readNWISuv`), try this:

```r
uvAvailability <- whatNWISsites(huc=10190005, hasDataTypeCd="iv")
uvData <- whatNWISdata(uvAvailability$site_no, service = "uv")
```
This brings back 8 sites, that measure, with either discharge or gage height.

I'm not sure what gages-II data/attributes are, could you explain more?

**Comment by mccreigh** [comment]
Thanks! That makes more sense, I was going down the wrong path. Using whatNWISSites returns a bit less detailed, even with siteOutput='expanded' - which had no affect for my test HUC, but the filtering options you show give more usable data to work from. 

Gages-II has shape files, which I wouldnt expect to be available, but it also has basin attribute information, which I just dont want to make sure I'm missing out on if it is available via dataRetrieval:
http://water.usgs.gov/GIS/metadata/usgswrd/XML/gagesII_Sept2011.xml

Thanks for your help,
James

**Comment by ldecicco-USGS** [comment]
You can get the siteOutput='expanded' like this:
```r
uvAvailability <- readNWISdata(huc=10190005, hasDataTypeCd="iv", 
                               siteOutput='expanded', 
                               service = "site")
```

`whatNWISsites` forces the returned data in a 'mapper' format. It's a very efficient return, but doesn't allow the expanded argument. `readNWISdata` is designed to be the most flexible and powerful function.

**Comment by ldecicco-USGS** [comment]
I just got a little overview on the gagesII data. Looks like a great set of info. I'm not sure how feasible it is, but I'll create a separate issue.
