### ISSUE TITLE
StateCode

### ISSUE THREAD

**Issue by hdugan** [USGS-R/dataRetrieval#102]
It would be fantastic to have a function to convert state codes (or county codes) to character names.

**Comment by jread-usgs** [comment]
Agreed. We were just talking about this 2 weeks ago. :+1:

**Comment by hdugan** [comment]
It is ridiculously hard to find a formatted table online....

**Comment by jread-usgs** [comment]
@ldecicco-USGS has a link, which I forgot after she shared it.

**Comment by ldecicco-USGS** [comment]
http://www2.census.gov/geo/docs/reference/state.txt

But yeah, I agree, we can add a table in the next release.

**Comment by ldecicco-USGS** [comment]
Here's county:

http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt

**Comment by hdugan** [comment]
Amazing. Thx :+1:

**Comment by ldecicco-USGS** [comment]
For the record, there's a lot of really good information here on all sorts of codes and variable names and whatnot:

http://help.waterdata.usgs.gov/codes-and-parameters

**Comment by ldecicco-USGS** [comment]
OK, @jread-usgs 's dream is more than just add a data frame with state code info into the sysdata.rda file, but also make an intelligent translator. A la:

```r
readNWISdata(stateCd='WI')
readNWISdata(stateCd=55)
readNWISdata(stateCd='Wisconsin')
readNWISdata(stateCd='wisconsin')

readWQPdata(stateCd='WI')
```
And...likewise with counties.

That's not 100% trivial...I'll get to it eventually. If someone else wants to have a go at it, that would be super.

**Comment by ldecicco-USGS** [comment]
I'm pushing some updates to dataRetrieval right now. I put the tables in the sysdata.rda file. If anyone wants to work on the function to do all that stuff @jread-usgs wants, the tools are there. I'll make a release for GRAN, and actually want to push to CRAN pretty soon.
