### ISSUE TITLE
getNWISDaily

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#104]
From an email:
""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Back in January, I tried using `getNWISDaily` to pull groundwater water quality data and to my surprise (at the time) it worked!  However, in trying this stunt again today, it didn't work, which has me wondering if 1) `getNWISDaily` has been modified in such a way over the last couple of months to temporarily disable this functionality or 2) it was a fluke that it worked in the first place?  For example, gw site 390208119433201 and param code 00631 (nitrate) has data (see screen shot below), but the following script won't seem to pull the data.  Is there a new function for pulling gw data?  

Thanks for your consideration.  Best, Eric
```r
library(EGRET)
library(dataRetrieval)

StartDate <- ""  
EndDate <- ""
siteNumber <- "390208119433201"
QParameterCd <- "00631"
Daily <- readNWISDaily(siteNumber, QParameterCd, StartDate, EndDate)
```
proof that the data is there:

http://nwis.waterdata.usgs.gov/nwis/qwdata?site_no=390208119433201&agency_cd=USGS&format=serial_rdb

**Comment by ldecicco-USGS** [comment]
@emorway-usgs:
The proof that the data is there tells me that it is a 'qw' (water quality...not groundwater) parameter, so `readNWISSample` would be more appropriate. 

```r
Sample <- readNWISSample(siteNumber, QParameterCd, StartDate, EndDate)
```
There are also some functions in dataRetrieval (the functions you are using are from EGRET), that might fit your needs better, depending on what you are trying to do.

**Comment by lawinslow** [comment]
I will admit, the function overlap between dataRetrieval and EGRET makes my head hurt a bit.

**Comment by ldecicco-USGS** [comment]
Well, the 'current' idea is that if you are using EGRET, then you've got all the tools you need to do a complete analysis. Those overlapping functions are simply calls to dataRetrieval, then a call to a function that creates all of the date columns (Julian, month, etc). 

Of course, the real reason is that we designed the `readNWISDaily` / `readNWISSample` functions 4 years ago...there was no dataRetrieval package....and there wasn't the foresight to see that a complete dataRetrieval package would be so useful. Also, one of the goals was to get people with no experience in R up and running as quick as possible...that was the reasoning for all of the various date-type columns. The new user does not need to immediately jump into understanding all of R's date functions and interstices.  Enough people jumped into EGRET with this workflow, that it seemed important to maintain after creating dataRetrieval (just moved to EGRET). 

That all being said, there's no reason you couldn't do the dataRetrieval in dataRetrieval and the EGRET in EGRET (if that helps in trainings, for example):

```r
siteNumber <- '04085427'
startDate <- '2012-01-01'
endDate <- '2012-06-30'
pCode <- '00060'
dailyData <- readNWISdv(siteNumber,pCode, startDate, endDate)
names(dailyData) <-  c('agency', 'site', 'dateTime', 'code', 'value')
library(EGRET)
# EGRET is always in SI units, so the 35.3 is to convert cfs to cms:
Daily <- populateDaily(dailyData,35.314667)
```
