### ISSUE TITLE
How do we select NWIS sites that are crest stage gages only?

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/dataRetrieval#105]
From Anne @ NM Training.

**Comment by ldecicco-USGS** [comment]
I'm not sure off-hand. Does that mean gages that only take measurements during flooding? What is the 'normal' way to discover that information?

I'll look around here first:
http://waterservices.usgs.gov/rest/Site-Test-Tool.html

Then here:
http://help.waterdata.usgs.gov/

If I figure something out, I'll respond here.

**Comment by ldecicco-USGS** [comment]
It looks like that is a specific parameter code: 00062...
Code coming shortly.

**Comment by ldecicco-USGS** [comment]
There are other ways to filter geographically (bounding box, huc), but here's an example for New Mexico:

```r
library(dataRetrieval)
pCode <- "00062"
siteInfo <- readNWISdata(stateCd="NM", parameterCd=pCode, service="site")
data <- readNWISqw(siteInfo$site_no, pCode, "", "")

```
