### ISSUE TITLE
Include gagesII

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#107]

**Comment by jread-usgs** [comment]
Thought this was the `rages` package

**Comment by ldecicco-USGS** [comment]
?

**Comment by jread-usgs** [comment]
A geospatial R package that deals with watershed attributes and climate normals. Interfaces w/ dataRet, but probably is outside the scope of DR?

**Comment by ldecicco-USGS** [comment]
This is an actual package that currently exists? I can't find it. Or, one we want?

@lawinslow  showed me some non-shapefile gagesII data...that seemed more inline with how dataRetrieval works. Like, a beefed up site info data frame...that was created in 2003 (or something like that).

**Comment by lawinslow** [comment]
When I'm remote, I can't tell if you've resolved this in person or not. 

But yeah, Gages II is pretty much just the dataset. Jordan wants to do something more hard core, where the metrics in Gages II would be generated/calculated on the fly. Right @jread-usgs?

**Comment by jread-usgs** [comment]
Right :+1: !!

**Comment by mccreigh** [comment]
Laura-
are you actually planning to include gagesII attributes with DR? I have no
idea if this issue was prompted by my earlier inquiry.... I was just
wondering if any of the metadata sources might have indicated 0/1 on being
in gagesII or any of its non-spatial attributes.

I'm working with the "reference" subset right now. I can share what I do,
if you're interested. It should be applicable to the full set of
attributes.

James



On Wed, Apr 1, 2015 at 2:00 PM, Jordan S Read <notifications@github.com>
wrote:

> Right [image: :+1:] !!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/dataRetrieval/issues/107#issuecomment-88614165>
> .
>



-- 
-
******************************************************************************
James McCreight
cell: (831) 261-5149
office: (303) 497-8404
VoIP (to cell): (720) 432-2166

**Comment by mccreigh** [comment]
I started with a csv of the gages2 attributes exported from QGIS.
That csv is here:
https://github.com/mccreigh/rwrfhydro/tree/master/inst/extdata

I read it in with this routine:
https://github.com/mccreigh/rwrfhydro/blob/master/R/gages_2.R
Where you can see that I also did some stuff to find the HUC8's (that's how
I'm organizing my database... sort of arbitrary).

I save the RData files here
https://github.com/mccreigh/rwrfhydro/tree/master/data
feel free to use these. they are roughly .5MB.




On Wed, Apr 1, 2015 at 8:30 PM, James McCreight <mccreigh@gmail.com> wrote:

> Laura-
> are you actually planning to include gagesII attributes with DR? I have no
> idea if this issue was prompted by my earlier inquiry.... I was just
> wondering if any of the metadata sources might have indicated 0/1 on being
> in gagesII or any of its non-spatial attributes.
>
> I'm working with the "reference" subset right now. I can share what I do,
> if you're interested. It should be applicable to the full set of
> attributes.
>
> James
>
>
>
> On Wed, Apr 1, 2015 at 2:00 PM, Jordan S Read <notifications@github.com>
> wrote:
>
>> Right [image: :+1:] !!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-R/dataRetrieval/issues/107#issuecomment-88614165>
>> .
>>
>
>
>
> --
> -
>
> ******************************************************************************
> James McCreight
> cell: (831) 261-5149
> office: (303) 497-8404
> VoIP (to cell): (720) 432-2166
>



-- 
-
******************************************************************************
James McCreight
cell: (831) 261-5149
office: (303) 497-8404
VoIP (to cell): (720) 432-2166
