### ISSUE TITLE
Is there way to merge column output when using readNWISuv?

### ISSUE THREAD

**Issue by sbrady-usgs** [USGS-R/dataRetrieval#108]
I have a site where one sensor is discontinued for another.  These were assigned different DD numbers and returned in separate columns by readNWISuv.  Is there an easy way in R to merge the two into one column filling in the missing values?  Here is an example of such a site:

http://waterservices.usgs.gov/nwis/iv/?format=rdb&sites=07144100&startDT=2015-02-01&endDT=2015-04-01&parameterCd=63680

In this case, fill 96_63680 when 44_63680 is missing a value.

Thanks,
Steve

**Comment by jread-usgs** [comment]
I run into that too a lot :+1:

**Comment by ldecicco-USGS** [comment]
Here's a pretty simple base R way to do it:

```r
library(dataRetrieval)

site <- "07144100"
start <- "2015-02-01"
end <- "2015-04-01"
pCode <- "63680"

data <- readNWISuv(site, pCode, start, end)
names(data)[5] <- "old_cd"
names(data)[6] <- "old_va"
names(data)[7] <- "new_cd"
names(data)[8] <- "new_va"

data$new_cd[is.na(data$new_va)] <- data$old_cd[is.na(data$new_va)]
data$new_va[is.na(data$new_va)] <- data$old_va[is.na(data$new_va)]

```

I simplified the names, once you start having multiple DD numbers, the column names can get real messy. If this doesn't work like you were hoping...or doesn't make sense....let me know.
