### ISSUE TITLE
Bug when multiple codes

### ISSUE THREAD

**Issue by dlorenz-usgs** [USGS-R/dataRetrieval#113]
The daily streamflow data for "05270500" contain 2 codes for 2014-11-11. An extract of the WML is below. 

<ns1:value qualifiers="P" dateTime="2014-11-10T00:00:00.000">315</ns1:value>
<ns1:value qualifiers="P Ice" dateTime="2014-11-11T00:00:00.000">-999999</ns1:value>
<ns1:value qualifiers="P Bkw" dateTime="2014-11-11T00:00:00.000">-999999</ns1:value>
<ns1:value qualifiers="P Ice" dateTime="2014-11-12T00:00:00.000">-999999</ns1:value>
<ns1:value qualifiers="P Ice" dateTime="2014-11-13T00:00:00.000">-999999</ns1:value>
<ns1:value qualifiers="P Ice" dateTime="2014-11-14T00:00:00.000">-999999</ns1:value>

When the data are retrieved though 2014-11-10, or beginning on 2-014-11-12, no error/warning  is printed and the data look OK. If the retrieval overlaps that period, a weird message is printed and the data are coded as 1/0. See the example retrieval:

readNWISdv("05270500", "00060", "2014-11-10", "2014-11-12")
Aggregation function missing: defaulting to length
  agency_cd  site_no       Date X_00060_00003_cd X_00060_00003
1      USGS 05270500 2014-11-10                1             1
2      USGS 05270500 2014-11-11                2             0
3      USGS 05270500 2014-11-12                1             0

**Comment by ldecicco-USGS** [comment]
Yeah, I actually found a similar case on Friday. I think I have it fixed, will push here soon, and CRAN soon after.
