### ISSUE TITLE
Improve help files for read*data functions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#115]
Although the official arguments are `...`, getting at least the 'major' filters in the description would be super useful.

**Comment by ldecicco-USGS** [comment]
Add unifying arguments without screwing up current functionality:

stateCd
bBox
huc
startDate
endDate
parameterCd
siteNumbers
tz
characteristicName
characteristicType

others?

**Comment by lawinslow** [comment]
Yay autocomplete!

**Comment by ldecicco-USGS** [comment]
exactly
