### ISSUE TITLE
Incorrect input arguments listed for readNWISuv()

### ISSUE THREAD

**Issue by katherbreen** [USGS-R/dataRetrieval#116]
Hi,

The function inputs listed for the function readNWISuv() on the main dataRetrieval page are incorrect.  The inputs are listed as "Common 3, parameter code".  The help for the function lists the arguments as ""siteNumbers, parameterCd, startDate = "", endDate = "",
  tz = "".  Please update the main page - I had issues getting the correct data output the first few times I tried.

**Comment by ldecicco-USGS** [comment]
Good timing! I was just updating `dataRetrieval` and debating whether or not to keep that table (since it was out-of-date). I should have it updated by the end of the day.

**Comment by katherbreen** [comment]
Awesome! It's kind of nice to end the day doing some html editing.
