### ISSUE TITLE
functionality to look up pcode attributes

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#124]
Thought `pCodeToName` would let me do something like `pCodeToName('00300')`, but it is just a big-ol data.frame. 

We are looking for basic support for `units(pcode)` or something similar. Any help for the user here?

**Comment by ldecicco-USGS** [comment]
`units <- readNWISpCode('00030')[["parameter_units"]]` ?

If you are asking about USGS data, `readNWISpCode` is the function you want. If you are talking WQP, it's a little trickier.

**Comment by ldecicco-USGS** [comment]
I was just looking at what you are doing over in mda.streams, looks like you want to call by name (?). There's another way to do it too if you aren't too concerned about super-newly imported pCodes (here's the bare-boned base R way to do it, of course you could make a function or use dplyr or something):

```
unit <- parameterCdFile$parameter_units[parameterCdFile$srsname == "Zinc"]
#That will come back with a bunch, because there are a lot of pCodes that have the name 'Zinc'

unit <- parameterCdFile$parameter_units[parameterCdFile$parameter_nm == "Zinc, water, filtered, micrograms per liter"]
# This comes with just the unit for the very specific name.
```

Does that help?

**Comment by jread-usgs** [comment]
this is what I ended up doing:
```R
pCodeToName[pCodeToName$parm_cd=='00300',]$measureunitcode
```
just figured there might be some helper functions in DR for this

**Comment by ldecicco-USGS** [comment]
That data frame is mainly in the package to get characteristic names for USGS pCodes (for WQP purposes). I'd strongly recommend using readNWISpCode instead of that dataframe.

**Comment by jread-usgs** [comment]
ok, but the naming and exporting of that data.frame may be confusing to users. what it really is is `NWISpCodes`, right?

**Comment by ldecicco-USGS** [comment]
Closing this up. The moral of the story I think is to use `readNWISpCode`. Made the pCodeToName data frame internal to not confuse people.
