### ISSUE TITLE
reshape library interferes with readNWISdv

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/dataRetrieval#125]
Linked issue from EflowStats issue number 17 .

This works:

```R
library(dataRetrieval)
x_obs <- readNWISdv("02177000", "00060", "2009-10-01", "2013-09-30") 
```

This does not, returns NAs

```R
library(dataRetrieval)
library(reshape)
x_obs <- readNWISdv("02177000", "00060", "2009-10-01", "2013-09-30") 
```

**Comment by ldecicco-USGS** [comment]
Funky! Was thinking about switching to dplyr+tidyr instead of the current plyr+reshape2 anyway. I'll have a look.

**Comment by jread-usgs** [comment]
function name conflict? link to issue is https://github.com/USGS-R/EflowStats/issues/17

**Comment by ldecicco-USGS** [comment]
namespace conflict with melt. `reshape2` is much much superior to `reshape`...I hadn't had it loaded in so long, I never noticed the conflict.

**Comment by tmills-usgs** [comment]
I too have probably never loaded reshape

**Comment by ldecicco-USGS** [comment]
Such an annoying problem! The same problem happens for any melt command OR `gather` (from tidyr) if you for some reason load up reshape after loading reshape2 or tidyr. I would have thought tidyr would explicitly call reshape2's melt.

**Comment by jread-usgs** [comment]
wish this could be python-like:
`@importAs melt melty`

**Comment by ldecicco-USGS** [comment]
Here's the reason:

http://stackoverflow.com/questions/16896632/reshape-package-masking-preventing-melt-from-naming-columns

**Comment by ldecicco-USGS** [comment]
So, can't just `reshape2::melt`, need to `reshape2:::melt.data.frame`

**Comment by ldecicco-USGS** [comment]
OHHHH....we could do a pull request on tidyr!

**Comment by ldecicco-USGS** [comment]
But...using the `:::` is frowned upon on CRAN....back to the drawing board.

**Comment by ldecicco-USGS** [comment]
tidyr has to do a fairly extensive re-write to avoid this. I'm closing it as won't fix (can always revisit if it comes up again). Generally, try to avoid the reshape package for either reshape2 or tidyr, or the base R reshape function.

**Comment by jread-usgs** [comment]
@ldecicco-USGS do you want to warn with `.onLoad` if `reshape` is loaded too? (or is it if `reshape2` is loaded too...?)

**Comment by ldecicco-USGS** [comment]
that's a good idea. Only reshape, reshape2 is totally fine.

**Comment by jread-usgs** [comment]
yeah, that way you can keep it as a wontfix, but provide a little clue to future users that may run into it.
