### ISSUE TITLE
whatWQPsites - dropping stations

### ISSUE THREAD

**Issue by ssifleet** [USGS-R/dataRetrieval#133]
I just noticed an issue with the whatWQPsites (and also readWQPdata) function.

It seems some of the stations are dropped.

Example:
stations<-whatWQPsites(startDate = "06-10-2015")
Warning messages:
1: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string
2: In whatWQPsites(startDate = "06-10-2015") :
  2570 sites were expected, 1177 were returned

This query when applied through the WQP UI returns all 2570 sites.

Also the query
data<-readWQPdata(startDate = "06-10-2015")
returns 54,289 records for 2570 unique sites (MonitoringLocationIdentifier)
however the same warning above is thrown and the attributes(data)$siteInfo data frame has only 1177 unique sites (MonitoringLocationIdentifier)

**Comment by ldecicco-USGS** [comment]
Thanks for the report, I'll have a look today.

**Comment by ldecicco-USGS** [comment]
Fixed the problem. For the time-being, you can install the development version using the package `devtools`:

```r
library(devtools)
install_github("USGS-R/dataRetrieval")
```

I'll send an update to "GRAN" soon, which is a USGS development R repository soon. To add that repository to your R profile, paste into R:

```r
source("http://owi.usgs.gov/R/add_gran_repo.R")
```

If you run that script, you can get the GRAN updates automatically when you update packages. The fix will make it to CRAN at the next CRAN release. Thanks again.

**Comment by ssifleet** [comment]
Thanks!
