### ISSUE TITLE
expanded=TRUE not working correctly for QW data

### ISSUE THREAD

**Issue by jlthomps** [USGS-R/dataRetrieval#136]
Using readNWISqw, constructNWISURL, importRDB1 and readNWISdata, the argument for 'expanded' data attributes does not translate correctly to the URL (as, eg, &rdb_qw_attributes=expanded). It looks like the function(s) are using 'expanded=TRUE' to set 'qw_sample_wide=wide', which is not the same thing. In the REST URL, qw_sample_wide=wide results in a wide (rather than long) dataset, where each sample is one row of data, with multiple columns for different parameters. This format does not include the other columns included in the rdb_qw_attributes=expanded, such as anl_dt and result_lab_cm_tx. 

To illustrate, running:
urlQW <- constructNWISURL("450456092225801","70300",startDate="",endDate="","qw",expanded=TRUE)
results in the URL

http://nwis.waterdata.usgs.gov/nwis/qwdata?search_site_no=450456092225801&search_site_no_match_type=exact&multiple_parameter_cds=70300&param_cd_operator=AND&list_of_search_criteria=search_site_no,multiple_parameter_cds&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=previous_parm_cds&qw_attributes=0&format=rdb&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=value&qw_sample_wide=0

As you can see, this URL specifies rdb_qw_attributes=0 rather than rdb_qw_attributes=expanded. For the moment, in order to pull these extra result columns, I am modifying the url created by 'constructNWISURL'. So, 

urlQW <- constructNWISURL("450456092225801","70300",startDate="",endDate="","qw",expanded=TRUE)
qwData2 <- importRDB1(urlQW,asDateTime=TRUE,qw=TRUE,tz="")
urlQW2 <- gsub("rdb_qw_attributes=0","rdb_qw_attributes=expanded",urlQW)
qwData4 <- importRDB1(urlQW2,asDateTime=TRUE,qw=TRUE,tz="")

**Comment by ldecicco-USGS** [comment]
@jlthomps : can you install the latest:

```r
library(devtools)
install_github("USGS-R/dataRetrieval")
```

And mess around to see if everything looks right?
