### ISSUE TITLE
Precipitation Data

### ISSUE THREAD

**Issue by wsyoung-usgs** [USGS-R/dataRetrieval#137]
Are there any plans to expand the tool for Precipitation Data?

**Comment by jread-usgs** [comment]
@wendiyoung which precip data are you thinking of?

**Comment by wendiyoung** [comment]
parameter code 00045 - unit-values from water services for either 1 site or a list of sites for a start and end date/time?  I'm new to R so this may be available now, I'm just going by the dataRetrieval program description.

**Comment by ldecicco-USGS** [comment]
I think there was a decision to not make 00045 publicly accessible data by NWIS (not `dataRetrieval`). If you are within the firewall of the USGS, you can use these instructions to alter the URL to get private data:

https://github.com/USGS-R/dataRetrieval/issues/130

I think it was because generally the precipitation data doesn't meet the QA requirements to be publicly available on NWIS.  I have no good link/reference to back this up....I'll try to dig around my email to find out more information if you are interested.

**Comment by wsyoung-usgs** [comment]
Hello Laura,

If you recall, last year you helped me with the dataRetrieval package with
regards to pulling rain IV's from NWIS Web.  I was pulled in another
direction but am now revisiting this as I make plans to write a script
using R to compute maximum rainfall intensities for certain intervals
(30-min, 1-hr, 2-hr, 6-hr, 12-hr, and 24-hr.) given a network of USGS site
ID's.

Many years ago (late 1990's), I wrote a series of python and .ksh scripts
that pull 5-minute continuous rain from ADAPS for a specific event (usually
1, 2, and no more than 3 days total) and iterates through the various
intervals finding the max intensities for the key intervals and when they
occurred.  The output is a table with each site and corresponding interval
information.  With ADAPS being replaced in the near future with Aquarius, I
need to rewrite the existing software.

My question to you is if you know of anyone in the USGS that may have
already created R functions to do this type of computation?  Or, if you
know of anyone else that may benefit from this and would want to
collaborate?

Thank you.

*Wendi Young*
IT Specialist
USGS - South Atlantic Water Science Center
(704)344-6272
http://nc.water.usgs.gov

**Comment by ldecicco-USGS** [comment]
A script like that I think would be pretty straight-forward in R (I'd probably use `dplyr`, but there could be a variety of ways to go). I don't personally know anyone who does that exactly, but there certainly could be. 

Grabbing the data from Aquarius is not something I've had a chance to look into, but I've been told it will be easier than ADAPS. 

If you'd like any help on your script, let me know.

**Comment by wsyoung-usgs** [comment]
Hello Laura,

I'm sorry for the delayed response.  Just when I think I have some time to
work on this, I get pulled in another direction.

I have written a script (*ComputeMaxIntensities.R*)that computes maximum
rainfall intensities for 7 key intervals for a list of sites.  The script
will prompt for a sitefile (*CharMeckSites.csv*), starting date of the
storm, and ask how many days to evaluate.  It has very little error
checking built-in and is very specific to our network of raingages here in
Charlotte. All sites collect 5-minute continuous rainfall so this is
assumed and is hard-coded for now.

Example run for testing would be:

CharMeckSites.csv
2016-09-01
3


The problem is, it takes 20+ seconds to evaluate each site.  With a total
of 72 raingage sites in our network, that's over 20 minutes for each run of
the script.  If it's not too much trouble, would you please have a look at
my code to see how I may optimize to make it run faster?

Please see the attached files (main script, script with functions, and
sample sitefile).  Thank you in advance for your help.


*Wendi Young*
IT Specialist
USGS - South Atlantic Water Science Center
(704)344-6272
http://nc.water.usgs.gov

**Comment by ldecicco-USGS** [comment]
I don't think there's an attachment. If you want, you can email me that directly.

**Comment by wsyoung-usgs** [comment]
Okay. Let me know if you don't receive a zip file. Thanks
