### ISSUE TITLE
readNWISmeas error

### ISSUE THREAD

**Issue by dlorenz-usgs** [USGS-R/dataRetrieval#140]
Old measurement data do not always have the time in the measurement_dt field. On conversion to POSIXct, those data result in NA, which makes them useless and no way to recover the original dates.

I suggest inserting a new column measurement_tm that contains any text after the 10-character data in _dt and converting the _dt to class Date. Then you can append the DateTime column if you want to try to convert as POSIXct.

**Comment by ldecicco-USGS** [comment]
Good timing. I'm working on dataRetrieval this week

**Comment by ldecicco-USGS** [comment]
Any chance you have a site that I could use to test?

**Comment by dlorenz-usgs** [comment]
Meas05316840 <- readNWISmeas("05316840")

**Comment by ldecicco-USGS** [comment]
If you install the latest version on github:

```
library(devtools)
install_github("USGS_R/dataRetrieval")
```

Basically, I added a noon to the dateTime columns (if no time was listed). Then, if that time did need to be inserted, a new column was created dateFlag that flags the rows that have only a date precision to them. 

I'll keep this issue open awhile. I'll get more people to have a look to see if it's the way we want to go.

**Comment by dlorenz-usgs** [comment]
I'm sorry, but I do not think that it is acceptable to synthesize data. The
data provided to users must match the data in the system--if there is no
time, then there is no time. If you want to not convert measurement_dt and
create a new column of synthesized date-time, that would be OK, because you
can document that.
 And the installation should be

library(devtools)
install_github("USGS-R/dataRetrieval")

**Comment by ldecicco-USGS** [comment]
My reasoning to put the noon time in the measurement_dt column is to keep the output backwards-compatible. If measurement_dt is suddenly not a POSIXct column, that could screw up people's code. The new dateFlag column would then indicate when the noon time was added, and be an indicator for the precision of the POSIXct date/time.  I'm not super happy with the logical dateFlag column, but that column (or some modification of that column) combined with proper documentation would give the user the full information that the raw text gives. 

How about keeping measurement_dt as a POSIXct (with no noons...therefore dates show up as NAs), and add a measurement_date column (that would be a Date object)? I want to minimize any changes in current functionality.

**Comment by dlorenz-usgs** [comment]
OK, then you also need a measurement_time column that is character the
records the recorded time and some indicator of the original time zone code
in which the measurement was made.

**Comment by ldecicco-USGS** [comment]
I really struggled with trying to figure out why someone would want a column with the text of the time when they have dates in Date types and date/times in POSIXct types. But, it is tricky enough to tease-out that I finally gave in and just put it in there. Have a look.

I also want to add that it's always possible to get the 'raw' rdb output using:

```
  url <- constructNWISURL("05316840",NA,"","","meas")
  data <- importRDB1(url,asDateTime=FALSE)
```

This is why I'm hesitant to add columns that seemingly have redundant data. If a user really doesn't want to use the generated POSIX date/times, they can fall back on this workflow.
