### ISSUE TITLE
readNWISpeak fails when no peak flow available. 

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/dataRetrieval#141]
readNWISpeak fails when there is no peak flow available. It would be better to return a message indicating no data available.

```R
dataRetrieval::readNWISpeak("013138000", "", "")
```

**Comment by ldecicco-USGS** [comment]
Interesting. In most of the other NWIS services, a no data available comes back with a status that is not 200 (404 or something I forget). This returns the equivalent of 'it's all good' but with nothing there. I'll put in a fix, and probably bring it up with NWIS too.

**Comment by ldecicco-USGS** [comment]
@tmills-usgs Try out the dev version like this:
```
library(devtools)
install_github("USGS-R/dataRetrieval")
```
Let me know if you notice anything amiss.

**Comment by tmills-usgs** [comment]
Looks good on your end, need to fix in EflowStats now.
