### ISSUE TITLE
readWQPdata url encoding issue

### ISSUE THREAD

**Issue by ssifleet** [USGS-R/dataRetrieval#143]
I think some of the url encoding may be a bit off

This throws a 400, I think b/c it leaves a space in the url:
system.time(data<-readWQPdata(statecode="US:25",characteristicType="Organics, PCBs"))

Error in getWebServiceData(obs_url) : Status:400: Bad Request
For: http://www.waterqualitydata.us/Result/search?statecode=US:25&characteristicType=Organics, PCBs&sorted=no&mimeType=tsv

another example:
system.time(data<-readWQPdata(characteristicName="Temperature, water", countycode="US:37:183"))

running dataRetrieval_2.3.1

**Comment by ldecicco-USGS** [comment]
I've struggled with comma's in the WQP. If you use: `%2C+` you can get what you need for now. I thought I had fixed that, but I guess there's still a lingering issue.

```
system.time(data<-readWQPdata(statecode="US:25",characteristicType="Organics%2C+PCBs"))
   user  system elapsed 
   3.45    0.18  104.46 
```

**Comment by ldecicco-USGS** [comment]
If you install the latest version on github:

```
library(devtools)
install_github("USGS_R/dataRetrieval")
```

You can check that this issue is fixed. Please re-open if you still have some problems. I'll be doing a few more checks and tests before releasing it to GRAN or CRAN.
