### ISSUE TITLE
Water Quality retrieval issue with version 2.4.2 of dataRetrieval

### ISSUE THREAD

**Issue by cjhoard** [USGS-R/dataRetrieval#158]
I have a script, that had worked previously, that retrieves water quality information for a set of wells.  When I attempted to run the script again I received an error that I think might be due to the switch of using the readr package in the dataRetrieval package although I am not sure.  when I get to a particular well I receive the following error.  

`qwret<-readNWISqw("413437087150601", parameterCd = c("NUT","INN"),startDate = "",endDate = "")`
`Error in names(readr.data) <- header.names : 
  'names' attribute [33] must be the same length as the vector [1]`
I have no trouble with the rest of the wells that I am retrieving so it might be that something in the database changed for that well but I wanted to pass this along in case it is an issue with the update of the dataRetrieval package.

**Comment by ldecicco-USGS** [comment]
Thanks for the message, perfect timing!

I just merged a new release (4.2.3). Check and let me know if that fixes it for you. 

```
library(devtools)
install_github("USGS-R/dataRetrieval")
```

Just to check, are you expecting that this site comes back with no data? The raw url generated is:

http://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=413437087150601&sort_key=site_no&group_key=NONE&inventory_output=0&begin_date=&end_date=&TZoutput=0&param_group=NUT,INN&qw_attributes=0&format=rdb&qw_sample_wide=0&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=multiple_site_no

I don't *think* I've changed the url generation function anytime soon, but just double-checking.

**Comment by cjhoard** [comment]
Thanks I think this site should have no data returned (it has no nutrient or chloride data anyways). Anyhow, I installed the new release (2.4.3) and the code works fine now.  Whatever you changed seems to work so thank you for editing the package.
