### ISSUE TITLE
documentation for stateCd

### ISSUE THREAD

**Issue by dlorenz-usgs** [USGS-R/dataRetrieval#159]
The description of the columns in stateCd leaves much to be desired. Here's what the Census Bureau says--described ans (ANSI) Codes for the States:

FIPS State Code | Official United States Postal Service (USPS) Code | Name | Geographic Names Information System Identifier (GNISID) 

Those descriptions are precise. It is important to know that the first column is the FIPS code. And in particular the second column is the Postal Code, not the state abbreviation (USGS publications require the use of the abbreviation and not the postal code, so using the term abbreviation may confuse users).

**Comment by jread-usgs** [comment]
@dlorenz-usgs how about submitting a pull request with these changes applied to the package? It would be a great example of demonstrating how easy it is for collaborators to suggest changes to dataRetrieval and other packages. 

Thanks!

**Comment by dlorenz-usgs** [comment]
I'd do that if I were going to stick around for longer than a month. I'm
sure that are more suggestions, particularly on the documentation, but my
focus is on getting the remaining packages for which I am responsible in
publication.

**Comment by jread-usgs** [comment]
Ok, no problem. Thanks for the suggestion and good luck on the publications.
