### ISSUE TITLE
Error on `whatWQPsites` for Minnesota

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/dataRetrieval#167]
````
library(dataRetrieval)
sites <- whatWQPsites(statecode = "US:27")

Error in value[[3L]](cond) : 
  Error in function (type, msg, asError = TRUE) : Illegal or missing hexadecimal sequence in chunked-encoding
with url:http://www.waterqualitydata.us/Station/search?statecode=US%3A27&mimeType=tsv&sorted=no
````

````
> traceback()
8: stop(e, "with url:", obs_url)
7: value[[3L]](cond)
6: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), 
       names[nh], parentenv, handlers[[nh]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch({
       h <- basicHeaderGatherer()
       returnedDoc <- getURI(obs_url, headerfunction = h$update, 
           ...)
   }, warning = function(w) {
       warning(w, "with url:", obs_url)
   }, error = function(e) {
       stop(e, "with url:", obs_url)
   })
3: getWebServiceData(obs_url)
2: importWQP(urlCall)
1: whatWQPsites(statecode = "US:27")
````

Works Ok for other states. I can also hit the URL directly and get a TSV directly. I think it might be an issue with internal parsing?

dataRetreival v2.4.4

Found by @mhines-usgs

**Comment by mhines-usgs** [comment]
Perhaps of interest, is that this request worked fine last week...

**Comment by ldecicco-USGS** [comment]
@mhines-usgs what version of dataRetrieval do you have?

**Comment by mhines-usgs** [comment]
I just had 2.4.0 but just updated a few minutes ago to 2.4.4 and am retrying the request.. similar requests are successful (for WI and MI)

**Comment by ldecicco-USGS** [comment]
FYI (while I debug)....there's a easter egg in `dataRetrieval` that you can use numbers directly for the state codes if you want. So these are all the same:

```
sites <- whatWQPsites(statecode = "US:27")
sites <- whatWQPsites(statecode = 27)
sites <- whatWQPsites(statecode = "MN")
sites <- whatWQPsites(statecode = "Minnesota")
```

That could save you picoseconds OR MORE when constructing your state loops!

**Comment by jread-usgs** [comment]
:shaved_ice:

**Comment by mhines-usgs** [comment]
Ok, so call me a liar, but it worked now... Luke ran into it too. Maybe intermittent weirdness is going on?

**Comment by ldecicco-USGS** [comment]
I'm changing the default for WQP requests to be zip. That seems to solve this problem.

**Comment by ldecicco-USGS** [comment]
The latest PR changes all WQP requests to zip, and *I think* fixes MN (it's the biggest site hit for WQP). So, if you still have that problem, re-open.

**Comment by mhines-usgs** [comment]
Thanks Laura, I am still having some issues with timing out (assumption?) on MN. The error displays like

Request

```
retrievedData <- readWQPdata(statecode="27",characteristicName="Secchi depth", siteType="Lake, Reservoir, Impoundment")
```

Response

``
Error: Cannot read file D:/MKHData/necsc/necsc-lake-modeling/result.tsv
``

the result.tsv is empty

Similar requests for MI and WI (26 and 55) work fine.

**Comment by ldecicco-USGS** [comment]
So, I'll make the error more informative...but are you sure there's data?

**Comment by ldecicco-USGS** [comment]
Gah, apparently when I tried to get rid of my httr conversion, I wiped a lot of the zip conversion too.

**Comment by mhines-usgs** [comment]
I'll compare with data I grabbed last week. My computer just died but will confirm later.

**Comment by ldecicco-USGS** [comment]
Please re-open if the update hasn't solved the problem. The update is also available on GRAN now:

```
install.packages("dataRetrieval", repos="http://owi.usgs.gov/R")
```

**Comment by mhines-usgs** [comment]
Thanks @ldecicco-USGS, the problem of erroring out is solved and just getting warnings now, but I'm still not getting all the data I used to get (say around 12/31/2015 or shortly thereafter). I don't know if you want to talk further about this sometime but it's not blocking me, just troubling.

**Comment by ldecicco-USGS** [comment]
When I pick MN, Secchi depth, and Lake, Reservoir, Impoundment, on the WQP:

![image](https://cloud.githubusercontent.com/assets/1105215/12730570/26255c4c-c8f2-11e5-9f34-4f4be3ed5da9.png)

I get an empty file back from WQP (no dataRetrieval involvement). So...maybe you want to talk to Jim?

**Comment by mhines-usgs** [comment]
That makes sense, I'll follow up with him! Thanks.
