### ISSUE TITLE
readNWISpeak bug

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-R/dataRetrieval#171]
```
stations<-c("06011000")
peakdata1<-readNWISpeak(stations,startDate="",endDate="",asDateTime=FALSE)
peakdata2<-readNWISpeak(stations,startDate="",endDate="",asDateTime=TRUE)
```

The readNWISpeak only pulls dates that are formatted with a month, day, and year.  
In many cases the day of peak is unknown but the month and year is.
readNWISpeak does not pull dates that are only a month and year, and thus
 I can't get the year of the peak which is necessary for processing using various
USGS software and processing methods.
Using the USGS peak flow data retrieval you will see that there is a Month and Year
 associated 06011000 is shown but the readNWISpeak does not pull this information.
http://nwis.waterdata.usgs.gov/mt/nwis/peak?site_no=06011000&agency_cd=USGS&format=html

**Comment by ldecicco-USGS** [comment]
I'm just pushing up a solution that would propagate the argument "convertType". So, if you have the `devtools` package installed, you can install this development version like this

```
devtools::install_github("USGS-R/dataRetrieval")

library(dataRetrieval)
stations<-c("06011000")
peakdata3<-readNWISpeak(stations,startDate="",endDate="",convertType=FALSE)
```
The column "peak_tm" is now a character vector. You can use either base R or `lubridate` to pull out the year and months. The way I would probably do it is:

```
peakdata3$year <- as.integer(sapply(strsplit(peakdata3$peak_dt, "-"), function(x) x[1]))
peakdata3$month <- as.integer(sapply(strsplit(peakdata3$peak_dt, "-"), function(x) x[2]))
```

**Comment by ldecicco-USGS** [comment]
Please re-open if the update hasn't solved the problem. The update is also available on GRAN now:

```
install.packages("dataRetrieval", repos="http://owi.usgs.gov/R")
```
