### ISSUE TITLE
importWQP incomplete data return

### ISSUE THREAD

**Issue by jharcum** [USGS-R/dataRetrieval#175]
I got an incomplete data return from importWQP. The whatWQPsites works ok (returning 346 NWIS and 1760 storet sites); however importWQP only returns 298,407 out of 1,265,932 records. 

I went to the WQP portal web site and confirmed the number of sites and results. The WQP web site downloaded the results in about 3-4 minutes and seemed ok. My script is attached, can you advise?

[getData.txt](https://github.com/USGS-R/dataRetrieval/files/114667/getData.txt)

![datret](https://cloud.githubusercontent.com/assets/13320765/12763992/5c43f4ea-c9c5-11e5-8de6-50937223425a.PNG)

**Comment by ldecicco-USGS** [comment]
I've tried the request via my browser a few times, and sometimes I'm only getting partial results there too. So, it might be a Water Quality Portal issue, or, it might be a problem with my internet. But, I'm looking into.

**Comment by ldecicco-USGS** [comment]
We think this might be a WAF (web application firewall) issue. Are you making this request within the USGS firewall?

**Comment by jharcum** [comment]
Nope. Actually made a request from a home office (no affiliation with USGS or any other federal agency). (But I did have a 2nd colleague try and he got the same issue as me. After seeing your 1st response about getting a partial response from the WQP web site, I re-tried using the WQP web site and I ended up batting 1 for 2, i.e., one time i got a full response and the other time a partial response.

We did have a communication from the STORET@epa.gov folks that replied to us saying "Upgrade in progress, there may be a few hiccups in the core services as well. The service should be online later this afternoon". They were inferring this past Monday [01Feb] afternoon.

(P.S. Thank you for your prompt attention. )

**Comment by jharcum** [comment]
I noted that v2.4.8 was built/released on 2/5/2016. So, I retried readWQPdata. Same result. Tried somewhat smaller queries (smaller time window) and they seemed to work, but still no glory on my initial query. If it is of any help, I've added the console output below ... the 4 runs correspond to a 1999-2010, 1997-2010, 1996-2010, and 1995-2010 time periods. The first three runs return 523k, 679k, and 760k records returned.  The last run failed returning 708k records of 846k expected records.

![datret1](https://cloud.githubusercontent.com/assets/13320765/12897589/44f24a84-ce76-11e5-8d57-d27f62c3c549.PNG)

**Comment by ldecicco-USGS** [comment]
This is definitely a firewall issue on our part (Water Quality Portal...not dataRetrieval). Send me an email (ldecicco@usgs.gov) and I can send you the dataset directly. Then you can import with this (change the path):

```
dataWQP <- importWQP("C:/Users/ldecicco/Downloads/result (1).tsv", zip = FALSE)
```

**Comment by ldecicco-USGS** [comment]
I tried using the `httr` package instead of `RCurl` and still have the same problems. I was thinking though that since you already know the site numbers, you could request for the data via chunks:

```
siteTypeSel           <- c('Stream')
statecodeSel          <- c('US:24')
characteristicTypeSel <- c('Nutrient')
sampleMediaSel        <- c('Water')
startDateLoSel        <- c('01-01-1990')
startDateHiSel        <- c('01-01-2010')

sites     <- whatWQPsites(siteType=siteTypeSel, 
                          statecode=statecodeSel, 
                          characteristicType=characteristicTypeSel, 
                          sampleMedia=sampleMediaSel, 
                          startDateLo=startDateLoSel, 
                          startDateHi=startDateHiSel)

with(sites, table(ProviderName))

#Subset:
index <- 1:nrow(sites)
chunk <- split(index, ceiling(seq_along(index)/100))

results     <- readWQPdata(siteid=sites$MonitoringLocationIdentifier[chunk[[1]]],
                                 sampleMedia=sampleMediaSel, 
                                 startDateLo=startDateLoSel, 
                                 startDateHi=startDateHiSel) 

for(i in chunk[-1]){

  results_chunk     <- readWQPdata(siteid=sites$MonitoringLocationIdentifier[i],
                             sampleMedia=sampleMediaSel, 
                             startDateLo=startDateLoSel, 
                             startDateHi=startDateHiSel) 
  results <- rbind(results, results_chunk)
}


```

**Comment by jharcum** [comment]
Without actually running the code, yes that would seem to be an alternative. Thank you for the suggestion. Down the road, please do let me know when the issue has been resolved. (P.S. Did you get a sense of how many rows of results that I can reliably get, or is it a trial & effort sort of thing?)

Jon

**Comment by ldecicco-USGS** [comment]
My understanding is that it isn't actually a number of rows problem, it is a problem with some specific text in the file somewhere. We are working on trying to figure out that text in order to get an exception.
