### ISSUE TITLE
Error message using dataRetrieval

### ISSUE THREAD

**Issue by jmusgs** [USGS-R/dataRetrieval#181]
Using version 2.5.0 and getting this error message.

Things still seem to work ok, but just wanted to report this in case it is a problem, or wanted to find out if it might be a problem with my machine.

No encoding supplied: defaulting to UTF-8.

**Comment by ldecicco-USGS** [comment]
Yup, I fixed it but apparently never pushed the changes up. 2.5.1 should get rid of those warnings.
