### ISSUE TITLE
Retrieving Gauge height data

### ISSUE THREAD

**Issue by UserFeb2016** [USGS-R/dataRetrieval#182]
Hello- I am a beginner with respect to R programming. I installed the dataRetrieval package and would like to retrieve some gauge height data. Here is an example of the statement I am using.
data1<-readNWISdv("02310308", "00065", "2016-01-01", "2016-02-29")

The statement above returns no values but when I check in NWIS, the data are available. I used the same statement (after changing the parameter code to 00060) to retrieve discharge data and it worked. I am not sure where I m making the mistake. Any help will be greatly appreciated.

Thanks

**Comment by ldecicco-USGS** [comment]
Good question!
When I check what data that site has, it only has daily min and daily max gage heights. There's a argument in `readNWISdv` that is statCd. It is set by default to 00003 which indicates daily mean. To get the min and max:

```
data1<-readNWISdv("02310308", "00065", "2016-01-01", "2016-02-29",c("00001","00002"))
```

I

**Comment by UserFeb2016** [comment]
Thank you! It worked.
