### ISSUE TITLE
Getting more parameters than I specified

### ISSUE THREAD

**Issue by UserFeb2016** [USGS-R/dataRetrieval#200]
Hello-
I am using the dataRetrieval package to pull data for around 1500 sites. My parameter list consists of "00060","00065","62610","62611","62614","62615","63158","63160","72020". Earlier I was pulling the data for all sites in one go but I was getting the error 'URI too large'. As you suggested I tried 500 at a time and it worked. For the first set of sites, the data set I am getting has 45 variables. I am not sure why. I have 9 parameters so I should get 9 variables (?). However, I am getting additional columns such as NURF.DISCHARGE, STRUCTURE.DISCHARGE, PORT.FLOW, MAIN.GATES, TO.COMPUTE.GH, ORLANDO.DATA, INDEX.VELOCITY ...etc. These additional columns have NAs for some sites and have values for others. For the second of sites, I am getting 26 variables. What do these additional columns represent? Can I delete them? I am using stat_cd 00011. Any help will be greatly appreciated. Thanks!

**Comment by jread-usgs** [comment]
Hi @UserFeb2016 can you share the snippet of dataRetrieval code you are using here? That will help me diagnose.

**Comment by jread-usgs** [comment]
@UserFeb2016 I think I understand the issue. 

There are different data descriptors for some parameter codes, so you may get multiple columns that have different names specifying nuance to the measurement method. 

A couple of things that will make this easier to do:
1. only call one p_code per dataRetrieval call, that way you know that everything coming back is for that code and you don't need to try to figure out which descriptor belongs to which variable
2. make a decision as to which data column to use for each site, and condense the data based on that. The `dplyr` package is pretty good at doing this. 

I have an example of how I have done this is here: https://github.com/USGS-R/mda.streams/blob/develop/R/stage_nwis_ts.R#L117 in case it is helpful. 

```r
which.var <- select(site_data, -DateTime, -site_no) %>% 
        tidyr::gather() %>% group_by(key) %>% summarize(num_non_NAs = sum(!is.na(value))) %>% 
        filter(num_non_NAs==max(num_non_NAs)) %>% .$key[1] 
```
figures out which variable to use for a particular site, based on having the largest amount of non-NA data. 

Make sense?

**Comment by UserFeb2016** [comment]
@jread-usgs Thank you!
When I looked at the data again, I realized that every parameter does have a parameter code along with the name. I should have mentioned this before. So, for example, I have X_00060_00011 and X._Structure.Discharge._00060_00011, I should be just using X_00060_00011, right? I am not really interested in the measurement method.

**Comment by ldecicco-USGS** [comment]
It's tricky because maybe you do want those columns. For the example you gave...maybe the site is recording 2 discharge measurements. For the tech to tell them apart, they named one "Structure.Discharge".  

That being said...if you are doing a fairly large-scale data grab, and just want the "main" data, it's pretty safe to take the column X_00060_00011 (and x_pcode_statcd for other pcode/stat_cd combos)
