### ISSUE TITLE
readWQPdata - fewer results returned than expected

### ISSUE THREAD

**Issue by jjwill2** [USGS-R/dataRetrieval#203]
I used the code below to try to query all nutrient chemistry data from lakes in OR. There was a warning message: "In importWQP(urlCall, FALSE, tz = tz) :
27571 sample results were expected, 1611 were returned". Is there any way to address or troubleshoot these warnings? Doing the same query through the WQ portal web interface yielded 27,374 results. What is happening here?

OR_lake_data <-readWQPdata(
        
        # specify states
        statecode = "US:41",
        
        # specifies water samples
        ActivityMediaName = "water",
        
        # specifies lakes
        siteType = "Lake, Reservoir, Impoundment",
        
        # specifies parameter category
        characteristicType = "Nutrient")

**Comment by ldecicco-USGS** [comment]
Hmm...I just ran that query and got the 27571 rows of data back. My best guess is that it was a "glitch in the internet matrix"....either on WQP's end your yours (because I don't remember fixing anything recently that would affect that type of error).

That being said, try updating your packages, and if you want to get the bleeding-edge package that I just tested, install from github:

```
devtools::install_github("USGS-R/dataRetrieval")
```

Also, let me know if that doesn't help.

**Comment by jjwill2** [comment]
I still have the same problem running it this morning with a good internet connection, so I don't think it is an internet problem. I think there is a problem related to my installed version of httr. I got this error when I tried to run your installation code: 

"Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘httr’ 0.6.1 is being loaded, but >= 1.0.0 is required
ERROR: lazy loading failed for package ‘dataRetrieval’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/dataRetrieval’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/dataRetrieval’
Error: Command failed (1)"

I tried to re-install httr, but R seems to want to install the binary version (0.6.1) rather than the source version (1.1.0): 
"There is a binary version available (and will be installed) but the
  source version is later:
     binary source
httr  0.6.1  1.1.0"

Do you have any pointers for how to load the most recent version of httr? 

Here is my seessionInfo(): 

R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1         plyr_1.8.1          dataRetrieval_2.2.1
[4] httr_0.6.1         

loaded via a namespace (and not attached):
 [1] assertthat_0.1  DBI_0.3.1       digest_0.6.4    lubridate_1.3.3
 [5] magrittr_1.0.1  memoise_0.2.1   parallel_3.1.1  Rcpp_0.11.6    
 [9] RCurl_1.95-4.3  reshape2_1.4    stringr_0.6.2   tools_3.1.1    
[13] XML_3.98-1.1   
> 
Thanks.

**Comment by ldecicco-USGS** [comment]
It looks like you have an older version of a Mac, and and older version of R...the combination makes for installing packages from CRAN a bit trickier. 

First, if you can, update your R to 3.2.x (I think 3.2.4 is the latest). Then, doing a simple R package updates should get you httr 1.1.0.

If not, I'd try to install from source:

```
install.packages("httr", type="source")
```

If that doesn't work, let me know.

**Comment by jjwill2** [comment]
installing the latest version of R solved the problem. Thanks.
