### ISSUE TITLE
Getting error message with readNWISdata for DVs

### ISSUE THREAD

**Issue by stprinos** [USGS-R/dataRetrieval#204]
Hi,

I created a very simple R script to pull DV data. Copied below. The data is being retrieved for one site (254248080263801) but not the other. I have tried pulling just "254000080460001" but get the following error message. I tried a couple other sites but only 254248080263801.

Error in as.POSIXct.default(retval$dateTime, tzLib[tz = retval$tz_cd[1]]) : 
  do not know how to convert 'retval$dateTime' to class “POSIXct”

Copy of script

library(dataRetrieval)
library(dplyr)

sitelist <- c("254248080263801", "254000080460001") # This is the USGS station ID number
startDT <- as.Date("1974-10-01")
endDT <- as.Date("2014-09-30")
DailyValDat <- readNWISdata(sites = sitelist, parameterCd="72020", service="dv",
                            startDate=startDT,endDate=endDT) # pulling the data
plot(DailyValDat$dateTime,DailyValDat$X_72020_00001, type = "l", xlab = "Year", 
     ylab = "Water level in feet") # Plotting the data.

**Comment by stprinos** [comment]
Never mind - The problem was that the parameter code 72020 was only used for the one site, for the others it was  62610.

**Comment by ldecicco-USGS** [comment]
Sounds good!
