### ISSUE TITLE
15 minutes intervals

### ISSUE THREAD

**Issue by FelipeCarrillo** [USGS-R/dataRetrieval#219]
Hi;
Could you show me how to download flow data in 15 minutes, hourly intervals from a site near Sacramento CA?

**Comment by ldecicco-USGS** [comment]
You can only retrieve the data that is available, so if the discharge sensor is set for 15-minute intervals, that is what the `readNWISuv` function will return. You can use R to aggregate the 15 minute data to hourly, but `dataRetrieval` wouldn't do that directly.

I'm not sure exactly how you'd want to do the calculations, there are a lot of ways to go about it in R. `dplyr` is my go-to package for that kind of stuff. You could create a new column that is hours, group_by hours, and mutate to make a mean....but there are lots of other ways to do it too, pick your favorite.

**Comment by FelipeCarrillo** [comment]
Thank you..dplyr is my favorite as well ...

Sent from Yahoo Mail on Android 
 
  On Thu, May 12, 2016 at 7:32 AM, Laura DeCicco<notifications@github.com> wrote:   
You can only retrieve the data that is available, so if the discharge sensor is set for 15-minute intervals, that is what the readNWISuv function will return. You can use R to aggregate the 15 minute data to hourly, but dataRetrieval wouldn't do that directly.

I'm not sure exactly how you'd want to do the calculations, there are a lot of ways to go about it in R. dplyr is my go-to package for that kind of stuff. You could create a new column that is hours, group_by hours, and mutate to make a mean....but there are lots of other ways to do it too, pick your favorite.
