### ISSUE TITLE
Fix error caused by out-of-date lubridate package or provide more informative error message

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/dataRetrieval#234]
I have gotten a number of reports about the following error

fast_strptime(paste(readr.data[, paste0(i, "_dt")], readr.data[,  : 
  unused argument (lt = FALSE)

```
nwisimport<-readNWISqw(siteNumbers="09361500", parameterCd="IMM",expanded = FALSE, reshape = TRUE)
```

An error message informing the user this is due to a version issue with lubridate would help troubleshoot. Or perhaps a warning on package load?

**Comment by tmills-usgs** [comment]
This was forwarded to me from another user

**Comment by ldecicco-USGS** [comment]
So frustrating, the REAL fix would be to get R up update all dependencies properly. 

The other option is to drop that function and use base R. It's exceptionally faster (the `fast_strptime`).

I might also be able to check for the version of `lubridate`, and include that argument if appropriate.

I like the idea of a tryCatch on this particular error, with a message to update `lubridate`.

**Comment by tmills-usgs** [comment]
:clap:
