### ISSUE TITLE
public_srsnames link is incorrect

### ISSUE THREAD

**Issue by jkreft-usgs** [USGS-R/dataRetrieval#245]
A user pointed out that the link to the WQP public srs names link is incorrect

https://github.com/USGS-R/dataRetrieval/blob/master/vignettes/dataRetrieval.Rnw#L686

The link should be

http://www.waterqualitydata.us/public_srsnames/

**Comment by jread-usgs** [comment]
@wdwatkins please fix of you can

**Comment by jread-usgs** [comment]
@wdwatkins can you link to the commit or PR that fixed this issue? Something like 
fixed in #244

**Comment by wdwatkins** [comment]
fixed in commit 9fdccc9
