### ISSUE TITLE
Test new readr

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#255]
@wdwatkins ...could you install the development version of the `readr` package and test `dataRetrieval`? The new version is going to be released to CRAN in 10 days.

**Comment by wdwatkins** [comment]
Looks like it broke something in `importRDB1`.  I'll look into it more today.

**Comment by wdwatkins** [comment]
It has to do with it reading in times as all seconds.

**Comment by wdwatkins** [comment]
#257
