### ISSUE TITLE
could not find function

### ISSUE THREAD

**Issue by jcjaimes** [USGS-R/dataRetrieval#260]
I have not been able to get some quantity and quality parameters using the package. I use RStudio 0.99.903 and R 3.1.1.

First, I installed it:
`install.packages("dataRetrieval")`
`library("dataRetrieval", lib.loc="~/R/win-library/3.1")`

Here, I got:
> Error: object ‘full_join’ is not exported by 'namespace:dplyr'
> In addition: Warning message:
> package ‘dataRetrieval’ was built under R version 3.1.3 
> Error: package or namespace load failed for ‘dataRetrieval’

Then, I manually checked the box in Packages of RStudio. Later, defined common variables, and, try to get the data:
`siteNumber <- c("06795500")`
`parameterCd <- c("00060")`
`startDate <- c("2008-01-01")`
`endDate  <- c("2009-12-31")`
`startDate <- as.Date(startDate)`
`endDate <- as.Date(endDate)`
`rawDailyQ <- readNWISdv(siteNumber,parameterCd, startDate, endDate)`

But, I got the message:
> Error: could not find function "readNWISdv"

Any help is appreciated. Thanks.

**Comment by ldecicco-USGS** [comment]
Not knowing exactly your setup, I would leave the "lib.loc" as the default to let R figure it out itself. 

The following worked for me:

```
library("dataRetrieval")
siteNumber <- c("06795500")
parameterCd <- c("00060")
startDate <- c("2008-01-01")
endDate <- c("2009-12-31")
rawDailyQ <- readNWISdv(siteNumber,parameterCd, startDate, endDate)
```
(notice you don't have to convert to Date if you don't want to).

**Comment by jcjaimes** [comment]
Thanks for your response. I used your piece of code, but still is not working. Same errors are shown.

**Comment by ldecicco-USGS** [comment]
OK, I didn't see the pasted error message before. That message looks to me like you are using an old version of `dplyr` that might not have the function `full_join`. First...could you reply and tell me what version you have of `dplyr` so I can add that as a requirement (ie...needs >X version of dplyr).

Then, I'd either update (or re-install) `dplyr`...or update all of your packages (there's an "Update" button in the upper-right corner of the Packages tab in RStudio):

![update](https://cloud.githubusercontent.com/assets/1105215/17417809/e36fa54c-5a5a-11e6-8c7a-dd2ff837dfbf.png)

If *that* doesn't work, let me know.

**Comment by jcjaimes** [comment]
I ended upgrading my RStudio and R versions, installed the package for the first time, and called it later. Then, it runs just fine. I am able to get the data :+1:  
Thank you Laura.
