### ISSUE TITLE
xml2 updates

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#268]
- [x] Incorporate `getWebServiceData` function
- [x] Add option for "raw" data
- [x] Increase test coverage for increased risk

**Comment by ldecicco-USGS** [comment]
Possibly, break out `importWaterML1` to more internal functions to make testing easier

**Comment by wdwatkins** [comment]
Also related to yesterday's discussion - I tested an invalid xml file, and read_xml fails nicely.  Web service data is no longer going through read_xml with `getWebServiceData`, but I assume it would be caught.

**Comment by ldecicco-USGS** [comment]
- [ ] Sort by site_no
- [ ] Change the names in the statisticInfo attribute to remain backwards compatible:
- [ ] Move tz_cd column to far right
- [ ] For the siteInfo attribute, `dec_lat_va` and `dec_lon_va` need to be numeric
- [ ] get the "no value" value
- [ ] replace the "no value" value with NA
- [ ] change the noDataValue to NA in variableInfo attribute

**Comment by wdwatkins** [comment]
@ldecicco-USGS what do you mean by sort by site_no?

**Comment by ldecicco-USGS** [comment]
I think old fashioned `dataRetrieval` comes back sorted by increasing site_no then increasing dates. So, for:

```
bBoxEx <- readNWISdata(bBox=c(-83,36.5,-81,38.5), parameterCd="00010")
head(bBoxEx[,1:3]
  agency_cd  site_no   dateTime
1      USGS 03178000 1998-09-30
2      USGS 03185400 1998-09-30
3      USGS 03191500 1998-09-10
4      USGS 03193000 1998-09-30
5      USGS 03193742 1992-09-30
6      USGS 03193770 1977-06-30
```
Whereas I think this version sorts by decreasing site_no(?) and decreasing dates:
```
bBoxEx <- readNWISdata(bBox=c(-83,36.5,-81,38.5), parameterCd="00010")
head(bBoxEx[,1:3]
  agency_cd  site_no   dateTime
1      USGS 03527000 1950-09-30
2      USGS 03527000 1967-09-30
3      USGS 03526000 1998-09-30
4      USGS 03524500 2016-08-23
5      USGS 03490000 1970-12-31
6      USGS 03490000 2016-08-23
```

**Comment by wdwatkins** [comment]
Oh.  This version probably just comes back in whatever order the sites were given in.
