### ISSUE TITLE
readNWISuv factor warning, returns NA vals

### ISSUE THREAD

**Issue by suewherry** [USGS-R/dataRetrieval#271]
Hi!

I recently used the readNWISuv function again and am getting the following error:
Warning message:
In `[<-.factor`(`*tmp*`, ri, value = c(5.1, 4.3, 3.8, 6.1, 5.7,  :
  invalid factor level, NA generated

Sometimes the function can run and return the correct dataset but more often it returns NA values.  I don't remember having this issue before with readNWISuv, so I'm having a difficult time troubleshooting.

Thanks,
Susan

**Comment by ldecicco-USGS** [comment]
Could you paste the code you are using that gives you errors?

**Comment by suewherry** [comment]
Oh sure, I'm running it for several sites and parameters but here is one example:
readNWISuv(siteNumbers="422622122004000",parameterCd="62625",startDate="",endDate="",tz="America/Los_Angeles")

Also, I'm using RStudio with R version 3.1.1, if that might make a difference.

**Comment by ldecicco-USGS** [comment]
Hmm...I just ran that code and it worked for me. I would recommend updating your packages. If you are using RStudio, there's a handy button in your "Package" tab:

![update](https://cloud.githubusercontent.com/assets/1105215/17906689/01bb8308-693e-11e6-85ea-bb3cbe57d197.png)

If that doesn't work, could you paste the results of sessionInfo() here?

**Comment by suewherry** [comment]
Ahh yes, that seemed to help, looks like my whole system needed an update.  Thanks!
