### ISSUE TITLE
NGWMN 

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#273]
- [x] siteInfo lat/lon make numeric
- [x] lat_dec_va make lat/lon names consistent
- [x] 3 functions: 

```
readNGWMNsites <- function(featureID){
  c("featureOfInterest"))
}

readNGWMNlevels <- function(featureID){
"observation"
}

readNGWMNdata <- function(..., service = "observation"){
  service = c("observation", "featureOfInterest", "getCapabilities")
}
```
- [x] fix Notes/Warnings
- [x] add message that these functions are in flux and no future behavior/output is promised

**Comment by ldecicco-USGS** [comment]
Make a column "dateTime"....only populate with date/times that have a tz offset

Make date column (as a Date object)

Make time column (as character)

**Comment by ldecicco-USGS** [comment]
Multi sites

**Comment by ldecicco-USGS** [comment]
Get a little more information on OGC filtering

**Comment by wdwatkins** [comment]
Probably needs jread's retry wrapper for the web service call also

**Comment by wdwatkins** [comment]
Currently not working?  This was an included example in the docs.  Other sites work.
site <- "MBMG.892195"
data <- readNGWMNlevels(featureID = site)

**Comment by wdwatkins** [comment]
☝️ fixed.  

- [ ] add responsible party and contact link to attributes

**Comment by wdwatkins** [comment]
multi-site get observation calls are in the queue for remote team
