### ISSUE TITLE
allow non-DST options for tz (e.g., EST, CST, MST, PST)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/dataRetrieval#281]
My collaborators collect sensor data in the Northeast; their sensors all use EST only (no daylight savings time). For merging with USGS data, it would be easiest if dataRetrieval allowed them to request data with tz='EST', but this is currently not one of the options (https://github.com/USGS-R/dataRetrieval/blob/master/R/importWaterML1.r#L124). Would the fix be as simple as adding 'EST','CST', etc. to that `match.arg` call?

This is the specific R call they'd like to make (and there are probably others that would become available after adjusting `importWaterML1`):

``` r
> qdat2 <- 
    readNWISuv(
      siteNumbers='01092000', parameterCd=c('00060','00065'), startDate='2013-11-03', 
      endDate='2013-11-03', tz='EST') %>%
    renameNWISColumns()
```

This is what they'd like to see (note exactly 4 observations / hour even across the DST transition):

``` r
> qdat2[2:18,]
   agency_cd  site_no            dateTime Flow_Inst GH_Inst Flow_Inst_cd GH_Inst_cd tz_cd
2       USGS 01092000 2013-11-02 23:15:00      5050    5.19            A          A   EST
3       USGS 01092000 2013-11-02 23:30:00      5050    5.19            A          A   EST
4       USGS 01092000 2013-11-02 23:45:00      5020    5.18            A          A   EST
5       USGS 01092000 2013-11-03 00:00:00      5020    5.18            A          A   EST
6       USGS 01092000 2013-11-03 00:15:00      5070    5.20            A          A   EST
7       USGS 01092000 2013-11-03 00:30:00      5100    5.21            A          A   EST
8       USGS 01092000 2013-11-03 00:45:00      5130    5.22            A          A   EST
9       USGS 01092000 2013-11-03 01:00:00      5190    5.24            A          A   EST
10      USGS 01092000 2013-11-03 01:15:00      5210    5.25            A          A   EST
11      USGS 01092000 2013-11-03 01:30:00      5240    5.26            A          A   EST
12      USGS 01092000 2013-11-03 01:45:00      5240    5.26            A          A   EST
13      USGS 01092000 2013-11-03 02:00:00      5210    5.25            A          A   EST
14      USGS 01092000 2013-11-03 02:15:00      5160    5.23            A          A   EST
15      USGS 01092000 2013-11-03 02:30:00      5070    5.20            A          A   EST
16      USGS 01092000 2013-11-03 02:45:00      5020    5.18            A          A   EST
17      USGS 01092000 2013-11-03 03:00:00      5020    5.18            A          A   EST
18      USGS 01092000 2013-11-03 03:15:00      5020    5.18            A          A   EST
```

(I achieved this by running the 'currently possible' command below, then calling `qdat2 <- mutate(qdat, dateTime=lubridate::with_tz(dateTime, 'EST')); qdat2$tz_cd <- 'EST'`. A dataRetrieval solution would be better.)

This is what's currently possible (data selected to show the DST transition between rows 8 and 9):

``` r
> qdat <-
    readNWISuv(
      siteNumbers='01092000', parameterCd=c('00060','00065'), startDate='2013-11-03', 
      endDate='2013-11-03', tz='America/New_York') %>%
    renameNWISColumns()
> qdat[2:18,]
   agency_cd  site_no            dateTime Flow_Inst GH_Inst Flow_Inst_cd GH_Inst_cd            tz_cd
2       USGS 01092000 2013-11-03 00:15:00      5050    5.19            A          A America/New_York
3       USGS 01092000 2013-11-03 00:30:00      5050    5.19            A          A America/New_York
4       USGS 01092000 2013-11-03 00:45:00      5020    5.18            A          A America/New_York
5       USGS 01092000 2013-11-03 01:00:00      5020    5.18            A          A America/New_York
6       USGS 01092000 2013-11-03 01:15:00      5070    5.20            A          A America/New_York
7       USGS 01092000 2013-11-03 01:30:00      5100    5.21            A          A America/New_York
8       USGS 01092000 2013-11-03 01:45:00      5130    5.22            A          A America/New_York
9       USGS 01092000 2013-11-03 01:00:00      5190    5.24            A          A America/New_York
10      USGS 01092000 2013-11-03 01:15:00      5210    5.25            A          A America/New_York
11      USGS 01092000 2013-11-03 01:30:00      5240    5.26            A          A America/New_York
12      USGS 01092000 2013-11-03 01:45:00      5240    5.26            A          A America/New_York
13      USGS 01092000 2013-11-03 02:00:00      5210    5.25            A          A America/New_York
14      USGS 01092000 2013-11-03 02:15:00      5160    5.23            A          A America/New_York
15      USGS 01092000 2013-11-03 02:30:00      5070    5.20            A          A America/New_York
16      USGS 01092000 2013-11-03 02:45:00      5020    5.18            A          A America/New_York
17      USGS 01092000 2013-11-03 03:00:00      5020    5.18            A          A America/New_York
18      USGS 01092000 2013-11-03 03:15:00      5020    5.18            A          A America/New_York
```

**Comment by ldecicco-USGS** [comment]
The time zone you are looking for is "America/Jamaica".

This will be a future blog post....but let me know if that doesn't solve your problems.

See also:
https://github.com/USGS-R/dataRetrieval/issues/152

**Comment by ldecicco-USGS** [comment]
Also, "EST" (and other similar ones) aren't possible because throughout the world, that apparently means different things.

**Comment by aappling-usgs** [comment]
Oh, interesting. What about 'Etc/GMT+5'?
(and yes, thanks, America/Jamaica should work in the meantime)

**Comment by ldecicco-USGS** [comment]
Personally, I find the documentation more clear for "America/Jamaica" because I don't need to debate in my head if it's positive or negative GMT... but "Etc/GMT+5" works too 

I've typically referred to:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
as the canonical list (and both are there).

**Comment by aappling-usgs** [comment]
Yes, but "Etc/GMT+5" **doesn't** work:
```
> qdat <- readNWISuv(siteNumbers='01092000', parameterCd=c('00060','00065'), startDate='2013-11-03', endDate='2013-11-03', tz="Etc/GMT+5") %>% renameNWISColumns()
Error in match.arg(tz, c("America/New_York", "America/Chicago", "America/Denver",  : 
  'arg' should be one of “America/New_York”, “America/Chicago”, “America/Denver”, “America/Los_Angeles”, “America/Anchorage”, “America/Honolulu”, “America/Jamaica”, “America/Managua”, “America/Phoenix”, “America/Metlakatla”
```

**Comment by ldecicco-USGS** [comment]
Oh, that's right. My idea back in the day was to limit it to the "America" ones to limit what the user could do...so they wouldn't go off and do something dumb (and if they really wanted to use something else, they could get it in GMT and change pretty easily the output). I also vaguely thought that those  "Etc/GMT+5" type tz's didn't work the same on all operating systems (that's something I'd have to verify...but there was some issue like that a long time ago).

Do you think it's worth adding all those (the GMT+X)?  I'll definitely put in some effort soon into making a good, clear, once-and-for-all vignette/blog post instead adding more allowed TZ...but I kind of like limiting the TZ's to a handful I can explain (although I can see the benefit to adding those others...I'd just need to test that operating system issue).

**Comment by aappling-usgs** [comment]
I see your point and appreciate the guard against doing dumb things - I definitely do them =). 

Prohibiting 'EST' seems like a great policy given that it's OS-dependent. (Thanks, I didn't know that! I was a bit surprised that it worked with `with_tz`, actually...I think EST is also restricted in some other package, but can't remember which now. Is 'EST5EDT' in the same category?)

I do like the 'Etc/GMT+X' suite of timezones and have used those in many of my workflows - they're more clear to me than America/Jamaica, America/Phoenix, etc. when my sites are nowhere near those countries/states. It would be awesome if you wanted to add those.
