### ISSUE TITLE
Presentation of rloadest output in manuscripts

### ISSUE THREAD

**Issue by AllisonOliver** [USGS-R/dataRetrieval#285]
Hello all!  

Question about publishing results from rloadest...  Aside from load numbers, the model selected, and the number of samples, what additional diagnostics from a rloadest run are good practice to include in a manuscript (thinking supplementary material here)? In other words, what would the readers be interested in regarding interpreting the performance of the model?

Thank you for your help!

Allison

**Comment by ldecicco-USGS** [comment]
Hi Allison, do you mind reposting your question here:
https://github.com/USGS-R/rloadest/issues

You might a few more opinions (and, future people looking for those answers will see it there).

**Comment by AllisonOliver** [comment]
Sure, thank you!
