### ISSUE TITLE
Error upon install

### ISSUE THREAD

**Issue by supercasey** [USGS-R/dataRetrieval#295]
I get the following error when trying to load the dataRetrieval library, any ideas?

 library(dataRetrieval)
Error : object ‘RETRY’ is not exported by 'namespace:httr'
Error: package or namespace load failed for ‘dataRetrieval’

**Comment by ldecicco-USGS** [comment]
I think you need to update (at least) the `httr` package. I always recommend updating them all. If you are using an `httr` version < 1.0.0, it won't have the RETRY function. If you only specify to R to update a single package, it won't actually update the dependent packages, even if there's a requirement for a particular version....like in this case:

https://github.com/USGS-R/dataRetrieval/blob/master/DESCRIPTION#L30

Let me know if that doesn't help. Also if it doesn't, paste in your results from `sessionInfo`

**Comment by supercasey** [comment]
Thanks, got it, I was just hoping to get some stuff done without a full update and didn't realize httr was a package I needed to update.  It is working now, thx.

**Comment by ldecicco-USGS** [comment]
Super!
