### ISSUE TITLE
Support zip downloads for Water Quality Portal

### ISSUE THREAD

**Issue by jkreft-usgs** [USGS-R/dataRetrieval#302]
Something that EPA users have brought up is that it would be helpful to use the zip=yes parameter that is part of the WQP in getWQPData so that data over the wire is reduced.

**Comment by jkreft-usgs** [comment]
it looks like this is already possible.  I will follow up to see what the issue is

**Comment by ldecicco-USGS** [comment]
I haven't tried it in awhile...so if there are any issues, let me know. I remember we decided to not have zip as the default because it didn't actually speed up most downloads, and I couldn't figure out how to inject a user-agent.
