### ISSUE TITLE
Missing dv data

### ISSUE THREAD

**Issue by chanse-ford** [USGS-R/dataRetrieval#303]
I'm trying to get daily discharge data from all streams in the Michigan Lower Peninsula. When I run the code to pull the data it seems like it gets most of it, but when I look at individual sites at a small timescale (a few months) I notice there seems to be missing data points. I've checked these sites at these times on the USGS website and the days missing are online. I'm not sure what's causing some of these data points to drop out. My code for pulling the data and separating out the lower peninsula is below. I've also included a picture showing some of the sites with missing data. The date range for the figure is Nov. 2011-June 2012.
![data issues](https://cloud.githubusercontent.com/assets/25036714/22376816/7f1f01e8-e47d-11e6-9c3a-f2f816f2f293.jpeg)

```
start.date <- "2002-09-01"
end.date <- "2016-06-01"           
  
dfMILP <- readNWISdata(stateCd = "MI", parameterCd = "00060", startDate = start.date, endDate = end.date, service = "dv", siteType = "ST",
                       siteStatus = "active")
dfMILP <- renameNWISColumns(dfMILP)
siteInfo <- attr(dfMILP, "siteInfo")


dfMILP <- subset(dfMILP, siteInfo$dec_lat_va <= 45.2744)
dfMILP <- subset(dfMILP, siteInfo$dec_lon_va >= -86.575)
```

**Comment by ldecicco-USGS** [comment]
Hmmmmm.....
I'll have a look. I do see all the data if I use the `readNWISdv` function. I'm not sure what the siteStatus="active" does, or if there's a problem in the parsing. I'll take a look.

In the meantime, you could do this instead:
```
start.date <- "2002-09-01"
end.date <- "2016-06-01"           

sites <- readNWISdata(stateCd = "MI", parameterCd = "00060", 
                       startDate = start.date, endDate = end.date, 
                       service = "site", siteType = "ST",
                       siteStatus = "active", 
                       seriesCatalogOutput=TRUE)
library(dplyr)
lowerP <- sites %>%
  filter(dec_lat_va <= 45.2744, dec_long_va >= -86.575) %>%
  filter(parm_cd == "00060", data_type_cd == "dv")

FlowData <- readNWISdv(lowerP$site_no, "00060", start.date, end.date)
FlowData <- renameNWISColumns(FlowData)

subFlow <- filter(FlowData, site_no == AuSab)
ggplot(data = subFlow) +
  geom_point(aes(x = Date, y = Flow), color = "red") +
  xlim(as.Date(c("2011-11-01","2012-06-30")))
```

So, that gets just a site data frame first, and calls the data on only the sites you want.

**Comment by chanse-ford** [comment]
This works great. Thanks for the help!
