### ISSUE TITLE
readNWISpeak Question

### ISSUE THREAD

**Issue by chanse-ford** [USGS-R/dataRetrieval#305]
Is it possible to subset particular months across years using readNWISpeak command? I'm examining spring peak flow at multiple sites with a time span of about ten years, but just using the base readNWISpeak command I get annual peak flows, some of which occur in the summer/fall. Is it possible to just get the peak flows from say Jan-June across multiple years? Thanks for any help.

**Comment by ldecicco-USGS** [comment]
I think the "peak" service only provides annual discharge and/or gage height. You might want to look at the "readNWISstat" function. There's an option to get daily, monthly, or annual stats on discharge. Have a look at the help file (?readNWISstat), and let me know if you have any questions.
