### ISSUE TITLE
Simplify user agent?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#307]
Currently our user agent is super specific to the user. The idea was that we could use this information to potentially help troubleshoot. However, so far, we've only used the user-agent to gather statistics on dataRetrieval usage. Because there are so many ua's, we may be losing some info since only the top 40 user-agents are listed in our user-agent logs. 

My question is, how important to we value potential troubleshooting info (that we've never used) vs a slightly more accurate view on our NWIS usage?

**Comment by jread-usgs** [comment]
Perhaps we can push for the logging to be modified to keep diverse UAs
