### ISSUE TITLE
readNWISpeak call

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/dataRetrieval#308]
```
sites <- c("02110500", "02130900", "02131110", "02131309","02131320", "02131472", "02131500", "02132000","02132100", "02132500", "02135000")
df <- readNWISpeak(sites)
```

```
Error in if (any(nchar(as.character(data$peak_dt)) <= 7) | any(grepl("[0-9]*-[0-9]*-00",  : 
  missing value where TRUE/FALSE needed
```

The NWIS url is ok.  This is happening somewhere inside `importRDB1`.

**Comment by ldecicco-USGS** [comment]
I'll have a look. To get the data right now though, you could do:
```
df <- readNWISpeak(sites, convertType = FALSE)
```

**Comment by wdwatkins** [comment]
actually I think is line 143 of readNWISunit

**Comment by ldecicco-USGS** [comment]
Yup

**Comment by ldecicco-USGS** [comment]
I guess we just need a `na.rm = FALSE` in those `any` calls.

**Comment by wdwatkins** [comment]
It is this line in the RDB that causes it:

`USGS	02135000	1928-09-00	`

`rm.na` loses the date - should we put something in to test for a `00` day?  This seems like it should be just reported without a day.

https://nwis.waterdata.usgs.gov/usa/nwis/peak/?site_no=02110500,02130900,02131110,02131309,02131320,02131472,02131500,02132000,02132100,02132500,02135000&range_selection=date_range&format=rdb

**Comment by wdwatkins** [comment]
@ldecicco-USGS what do you think? ☝️

**Comment by ldecicco-USGS** [comment]
Hmm... in most services, I would want to be very concerned with something that had a date "1928-09-00". It sort of makes sense in the peak flow services, which is why we have the extra logic in the `readNWISpeak` function. I'd say at a minimum, we add `na.rm = FALSE` to the `any` function in `readNWISpeak`. I'm less sure I want the RDB to convert that to any sort of POSIX'y date. I think I like it coming back as NA. (To me) that tells the user, use `convertAsDate` to FALSE, so they can see what's raw services coming back as.

**Comment by wdwatkins** [comment]
Why wouldn't we want to it default to `convertType = FALSE` though if there is a date like this though?  Isn't that the behaviour for some other functions?

**Comment by ldecicco-USGS** [comment]
(my opinion, I could be wrong).... we do that in some of the other functions that call `importRDB`. If we did it directly in `importRDB`...we would prohibit the user from being able to say "yes, convert all the dates that you can, and make the rest `NA`"

**Comment by wdwatkins** [comment]
Ah ok that makes sense.  Maybe just a message then that some dates could not be converted?

**Comment by ldecicco-USGS** [comment]
For sure!

**Comment by ldecicco-USGS** [comment]
just the message on the importRDB.
