### ISSUE TITLE
Explore combining USGS & NGWMN water ml2 parser

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#321]

**Comment by wdwatkins** [comment]
There are some differences in the metadata supplied with each time-value pair:
https://cida-test.er.usgs.gov/ngwmn_cache/sos?request=GetObservation&service=SOS&version=2.0.0&observedProperty=urn:ogc:def:property:OGC:GroundWaterLevel&responseFormat=text/xml&featureOfInterest=VW_GWDP_GEOSERVER.USGS.305736084355801

https://waterservices.usgs.gov/nwis/dv/?site=04085427&format=waterml,2.0&ParameterCd=00060&StatCd=00003&startDT=2012-01-01&endDT=2012-06-30

Qualifier/category/value vs comment and source.  It could be doable though to account for both

**Comment by wdwatkins** [comment]
Probably best to keep two functions that read the header, and then call a common `importWaterML2Timeseries` or something function

**Comment by ldecicco-USGS** [comment]
This task is done with #345 
I think we might want to make a separate task to create the logic in `importWaterML2` to handle defaults, a particularly important feature of WaterML2
