### ISSUE TITLE
Pull out URL building logic in the WQPdata calls

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#324]

**Comment by ldecicco-USGS** [comment]
@lindsaycarr can you do this first? I'd make it an internal function maybe name it something like `readWQPdots`? That is, pull out all the logic in `readWQPdata` up until line 179. I think that will be the exact code that can then just be plopped in `readWQPsites`, `whatWQPsites`, and `whatWQPdata` (that I'm about to push).

**Comment by lindsaycarr** [comment]
Are you sure it is until 179? That doesn't seem like that would fit in this function. I imagine the usage is `values <- readWQPdots(...)` where a named vector is returned. https://github.com/USGS-R/dataRetrieval/blob/master/R/readWQPdata.R#L104-L146

**Comment by ldecicco-USGS** [comment]
Oh sorry, I added some examples so I have a lot more lines than the upstream master. Yeah, on master it's 104. If travis ever kicks off...I assume I'll merge #301 , then it will be 179(ish...)
