### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/dataRetrieval#337]
- [x] `siteNumber` vs `siteNumbers` (@ldecicco mentioned that every function might be able to handle more than one site now)
- [ ] ~~`statType` is used in `readNWISstat`, but `statCd` is used in `readNWISdv`~~
- [x] `readNWISpeak` documentation says that the default is to drop incomplete dates. That does not seem to be the case any more (see below). 

```r
flsite_peak <- readNWISpeak(siteNumber="02235200")
length(which(is.na(flsite_peak$peak_dt)))
[1] 1

flsite_peak_incomp <- readNWISpeak(siteNumber="02235200", asDateTime=FALSE)
length(which(is.na(flsite_peak_incomp$peak_dt)))
[1] 1
```

**Comment by ldecicco-USGS** [comment]
`statType` I think is different than `statCd`, so that's actually correct I think. 

`statCd` is like '00003', `statType` is 'mean'

**Comment by wdwatkins** [comment]
Yeah, the stats service doesn't use the codes

**Comment by ldecicco-USGS** [comment]
Looking through, I think it's only `constructNWISurl` that still had a `siteNumber` argument.

**Comment by ldecicco-USGS** [comment]
The times you mostly see `siteNumber` are variable names in examples. I'll change those across the board to something completely different to try to avoid confusion.

**Comment by lindsaycarr** [comment]
I noticed that you can use "sites" as the argument name sometimes and it works, too.

**Comment by ldecicco-USGS** [comment]
`sites` is a variable that is allowed with the `...`'s, but I don't think it's ever an official function argument. So, it's part of waterservices.usgs.gov options, but never a defined parameter.
