### ISSUE TITLE
Consider renameNWIScolumns with groundwater?

### ISSUE THREAD

**Issue by arhoades-usgs** [USGS-R/dataRetrieval#342]
```r
gwSite_data <- readNWISdata(service="gwlevels", 
                            siteNumbers="350946106205401",
                            parameterCd = "72019",
                            startDate = "1980-01-01")
names(gwSite_data)
 [1] "agency_cd"          "site_no"            "site_tp_cd"        
 [4] "lev_dt"             "lev_tm"             "lev_tz_cd_reported"
 [7] "lev_va"             "sl_lev_va"          "sl_datum_cd"       
[10] "lev_status_cd"      "lev_agency_cd"      "lev_dt_acy_cd"     
[13] "lev_acy_cd"         "lev_src_cd"         "lev_meth_cd"       
[16] "lev_age_cd"         "lev_dateTime"       "lev_tz_cd" 
```

**Comment by ldecicco-USGS** [comment]
The `renameNWIScolumns` function is mostly useful for giving commonly used parameter codes and statistic codes "human friendly" names (So, 00060_00003 would turn into Flow_Mean). The column names in the groundwater service are already rather readable. 

There are fairly straightforward ways to change the name of columns using both base R or `dplyr` (also, the `data.table` package has a nice solution that I'm not including here).

Say you only want to change `lev_va` to "results", in base R you could:

```r
names(gwSite_data)[names(gwSite_data) == "lev_va"] <- "results"
```

Using the `rename` function in `dplyr`:

```r
library(dplyr)
gwSite_data <- rename(gwSite_data, results=lev_va)
```

If there are several columns ("lev_va" to "results" and "lev_dt" to "Date" for example):

```r
library(dplyr)
gwSite_data <- rename(gwSite_data, 
                             results=lev_va,
                             Date = lev_dt )
```

or base:
```r
names(gwSite_data)[names(gwSite_data) == "lev_va"] <- "results"
names(gwSite_data)[names(gwSite_data) == "lev_dt"] <- "Date"
```
That might feel clunky, so you also could do this....but you need to be very careful then about using the correct index:
```r
names(gwSite_data)[c(7,4)] <- c("results","Date")
```

**Comment by lindsaycarr** [comment]
I'll share with the class from this week! Thanks for the info, Laura!

**Comment by arhoades-usgs** [comment]
Thanks Laura!
