### ISSUE TITLE
importRDB with leading zero's in the dates

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#373]
It was suggested using `importRDB1` from `dataRetrieval` to read the ADAPS output I have. That almost works, but it doesn't seem to understand the hhmmss field when that has leading zeroes; in that case it is giving me NA for DATETIME.

FYI, for a workaround I read the file with importRDB1 with convertType=F and then used lubridate::ymd_hms, with tz="America/Belize" for the "CST" equivalent to create the DATETIME field. I mention this because importRDB1 only accepts tz="America/Managua" for the "CST" equivalent, and that did not always work for me, so if they perhaps have some underlying code in common, tz="America/Belize" might be better (though why they'd be any different, I don't know).

**Comment by lindsaycarr** [comment]
@ldecicco-USGS any example at all you can help me with? Not really following where this would happen.

**Comment by lindsaycarr** [comment]
I might be missing something here, but I ran the example and don't get NAs for observations with a time that has leading zeros.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS can you run this with the `.GHt` file we were sent and tell me if you see NAs in `DATETIME`?

```
stage_data <- importRDB1("adaps_example_file.GHt", convertType = TRUE)
anyNA(stage_data$DATETIME)
[1] FALSE
```

**Comment by ldecicco-USGS** [comment]
When I run that, yes....I don't get NA's but I also don't get dateTimes:

```
stage_data <- importRDB1("C:/Users/ldecicco/Downloads/USGSBIOIN_GH.RDB", convertType = TRUE, asDateTime = TRUE)
str(stage_data$DATETIME)
chr [1:53516] "07/25/2012 17:00:00" "07/25/2012 18:00:00" ...
```

**Comment by ldecicco-USGS** [comment]
Confirmed this is fixed. Maybe a `readr` update fixed it.
