### ISSUE TITLE
return more helpful errors?

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/dataRetrieval#374]
The failed query, just says "Bad Request". It would be nice to get more helpful errors and the returned URLs appear to have them sometimes.

```
bbox <- c(-92.821445, 42.303044, -92.167168, 42.646524)
sites <- whatNWISsites(stateCd="IA", bBox=bbox)
Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 1 seconds...
For: https://waterservices.usgs.gov/nwis/site/?stateCd=IA&bBox=-92.821445,42.303044,-92.167168,42.646524&format=mapper

Error in getWebServiceData(urlCall, encoding = "gzip") : 
  Bad Request (HTTP 400).
```

The message in the URL is actually very helpful (https://waterservices.usgs.gov/nwis/site/?stateCd=IA&bBox=-92.821445,42.303044,-92.167168,42.646524&format=mapper).

`syntactic error: Only one Major filter can be supplied. Found [bbox] and [stateCd]. Please remove the extra major filter[s]., server=[caas01]`

**Comment by ldecicco-USGS** [comment]
Yeah, this shouldn't be too hard to do now that we've got `httr` set in there. We could check for 400 here:

https://github.com/USGS-R/dataRetrieval/blob/master/R/getWebServiceData.R#L34

And parse the html (which, I think httr will do very easily) to put into a warning
