### ISSUE TITLE
readNWISdv failure

### ISSUE THREAD

**Issue by chanse-ford** [USGS-R/dataRetrieval#380]
Whenever I try to download stream data using "readNWISdv" I keep getting the response `Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 2 seconds...
For: https://waterservices.usgs.gov/nwis/dv/?site=4001000&format=waterml,1.1&ParameterCd=00060&StatCd=00003&startDT=2016-10-01&endDT=2016-11-01

Error in getWebServiceData(obs_url, encoding = "gzip") : 
  Bad Request (HTTP 400).`

I've tried uninstalling/reinstalling the package but still getting the error. Any help would be greatly appreciated.

**Comment by chanse-ford** [comment]
When running the code it has the leading zero. It looks like:
`test <- readNWISdv(04001000, "00060", "2016-10-01", "2016-11-01")`

**Comment by ldecicco-USGS** [comment]
Add quotes around the 04001000, because if you don't quote it, R thinks it is a number, and that's how the leading zero is lost.

**Comment by chanse-ford** [comment]
Rookie mistake! Haha. Thank you so much.
