### ISSUE TITLE
readNWISuv for a site with multiple sonde depths

### ISSUE THREAD

**Issue by toddlester** [USGS-R/dataRetrieval#387]
Hey, 

I was wondering how dataRetrieval / readNWISuv 'works' with sites such as 0217206935, where there are two sondes deployed at different depths?  They both have the same P-code, so if I was using:

WT <- as.data.frame(readNWISuv(usgsST, "00010", start, end, tz = "America/Jamaica")) 

which value is it really pulling?  is there anyway to designate 00010 from the top, and then 00010 from the bottom sonde?

Thanks!!!

Todd

**Comment by toddlester** [comment]
Whoops, neverrmind...   I jumped the gun on creating that issue...  I see that pulling 00010 will create two columns, one with top, one with bottom data...

coffee needs to kick in I suppose...  sorry!!!!!

**Comment by jread-usgs** [comment]
☕️ 
Here is what that looks like for others w/ the same question:
```r
library('dataRetrieval')
WT <- readNWISuv(siteNumbers = c("0217206935"), parameterCd = "00010")

head(WT)
  agency_cd    site_no            dateTime X_00010_00000 X_00010_00000_cd
1      USGS 0217206935 2016-06-30 18:15:00          28.9                P
2      USGS 0217206935 2016-06-30 18:30:00          28.9                P
3      USGS 0217206935 2016-06-30 18:45:00          28.9                P
4      USGS 0217206935 2016-06-30 19:00:00          28.9                P
5      USGS 0217206935 2016-06-30 19:15:00          28.9                P
6      USGS 0217206935 2016-06-30 19:30:00          28.9                P
  X_BOTTOM_00010_00000 X_BOTTOM_00010_00000_cd tz_cd
1                 28.6                       P   UTC
2                 28.6                       P   UTC
3                 28.6                       P   UTC
4                 28.6                       P   UTC
5                 28.7                       P   UTC
6                 28.7                       P   UTC
```
