### ISSUE TITLE
No data value not turning into NA

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#392]
https://nwis.waterservices.usgs.gov/nwis/iv/?site=50024950,50027600,50031200,50035000,50038100,50038320,50039500,50043000,50043800,50045010,50046000,50049100,50051800,50055000,50055750,50057000,50106100,50113800,50114900,50136400,50138000,50144000,50147800,50148890&format=waterml,1.1&ParameterCd=00065&startDT=2017-09-17&endDT=2017-09-20

https://github.com/USGS-R/dataRetrieval/blob/master/R/importWaterML1.r#L271

that line is showing FALSE when it needs to be TRUE

**Comment by wdwatkins** [comment]
Should that be `names(obsDF)` maybe?  I don't think `nObs` would ever have any names, so this would always evaluate to false.  Comes from here: https://github.com/USGS-R/dataRetrieval/commit/06ca1711f73ec755eba9f2e6b4d07e89716eb87d
