### ISSUE TITLE
Conflicting variableName and variableDescription

### ISSUE THREAD

**Issue by jasonelaw** [USGS-R/dataRetrieval#399]
I'm noticing a conflict between the `variableName` and `variableDescription` reported by `readUSGSdata` for parameter code 99137. However, the information on the USGS [parameter code lookup](https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes?pm_group=Nutrient&radio_pm_search=pm_search&pm_search=99137&casrn_search=&srsname_search=&format=rdb&show=parameter_group_nm&show=parameter_nm&show=casrn&show=srsname&show=parameter_units) appears correct.

Here's where I noticed it:
```
> str(readNWISdata(parameterCd=99137, siteNumbers=14211720, tz = 'America/Los_Angeles', service = 'iv'))
'data.frame':	1 obs. of  6 variables:
 $ agency_cd       : chr "USGS"
 $ site_no         : chr "14211720"
 $ dateTime        : POSIXct, format: "2017-10-25 06:30:00"
 $ X_99137_00000   : num 0.76
 $ X_99137_00000_cd: chr "P"
 $ tz_cd           : chr "America/Los_Angeles"
 - attr(*, "url")= chr "https://nwis.waterservices.usgs.gov/nwis/iv/?parameterCd=99137&sites=14211720&format=waterml,1.1&"
 - attr(*, "siteInfo")='data.frame':	1 obs. of  13 variables:
  ..$ station_nm          : chr "WILLAMETTE RIVER AT PORTLAND, OR"
  ..$ site_no             : chr "14211720"
  ..$ agency_cd           : chr "USGS"
  ..$ timeZoneOffset      : chr "-08:00"
  ..$ timeZoneAbbreviation: chr "PST"
  ..$ dec_lat_va          : num 45.5
  ..$ dec_lon_va          : num -123
  ..$ srs                 : chr "EPSG:4326"
  ..$ siteTypeCd          : chr "ST"
  ..$ hucCd               : chr "17090012"
  ..$ stateCd             : chr "41"
  ..$ countyCd            : chr "41051"
  ..$ network             : chr "NWIS"
 - attr(*, "variableInfo")='data.frame':	1 obs. of  7 variables:
  ..$ variableCode       : chr "99137"
  ..$ variableName       : chr "Nitrite, water, in situ,  mg/L as N"
  ..$ variableDescription: chr "Nitrate, water, in situ, milligrams per liter as nitrogen"
  ..$ valueType          : chr "Derived Value"
  ..$ unit               : chr "mg/l as N"
  ..$ options            : chr ""
  ..$ noDataValue        : logi NA
 - attr(*, "disclaimer")= chr "Provisional data are subject to revision. Go to http://waterdata.usgs.gov/nwis/help/?provisional for more information."
 - attr(*, "statisticInfo")='data.frame':	1 obs. of  2 variables:
  ..$ statisticCd  : chr "00000"
  ..$ statisticName: chr ""
 - attr(*, "queryTime")= POSIXct, format: "2017-10-25 10:08:58"
```

**Comment by wdwatkins** [comment]
What were you expecting to see in those fields?

**Comment by ldecicco-USGS** [comment]
Nitrate vs Nitrite, the funky thing is yeah, it comes back correct with `readNWISpCode` as well. I'll take a look.

**Comment by ldecicco-USGS** [comment]
Yeah, the actual descriptions in the "WaterML 1" are wrong if you scroll down to the bottom here:

https://nwis.waterservices.usgs.gov/nwis/iv/?parameterCd=99137&sites=14211720&format=waterml,1.1&

I'll notify someone at NWISweb and see if it's a bug. Thanks for the report!

**Comment by ldecicco-USGS** [comment]
I reported it and they should be updating the database. I'm not sure how long the update will take to trickle up to the NWISweb services, but you should see it corrected soon.

The response was:

"Thank you!!!  Many people seem to be aware of errors in the files but never say anything.  I need all the help I can get.  I've logged this in to be corrected in the next update. "

So, if you notice any other inconsistencies, let me know!
