### ISSUE TITLE
No records returned

### ISSUE THREAD

**Issue by joelnc** [USGS-R/dataRetrieval#402]
Nor sure if this is buggy or just user error.... but:

`whatNWISdata(siteNumbers="351032080475245", service="dv")` indicates 20+ years of daily precip records are available.

`readNWISdv(siteNumbers="350823080505345", parameterCd="00045")`, or with various start/end dates returns 0 records.

**Comment by ldecicco-USGS** [comment]
Looks like the stat code is "00006" (sum), and the default in `readNWISdv` is "00003" (mean) ....so try:
```
readNWISdv(siteNumbers="350823080505345", parameterCd="00045",statCd = "00006")
```

**Comment by joelnc** [comment]
User error indeed!  Thanks Laura.  Your contributions to the science are immense.
