### ISSUE TITLE
Unexpected Return Value from Function whatNWISdata

### ISSUE THREAD

**Issue by jasmyace** [USGS-R/dataRetrieval#403]
Hello,

I currently have a set of code that performs some querying, based on functions in `dataRetrieval`.  But, then my code broke.  

I find that function `whatNWISdata` no longer returns the full set of variables listed in the `Value` section of `help(whatNWISdata)`.  In my case specifically, I see that the function no longer returns `"parameter_nm"` and `"parameter_units"`.  When I run the help-file `Examples` section code of 
```r
# R version 3.4.2 (2017-09-28)
# Platform: i386-w64-mingw32/i386 (32-bit)
# Running under: Windows Server >= 2012 x64 (build 9200)
# dataRetrieval_2.7.3

availableData <- whatNWISdata(siteNumber = '05114000')
```
I confirm this behavior.  

I could believe that a DBA removed these from the query (outside the package scope), as I can see that both `"parameter_nm"` and `"parameter_units"` could be obtained from external tables, i.e., those found on the provided link in the help documentation.  

I suspect that the function and query are a-ok, and the roxygen documentation may need to be updated.  In this case, I can simply grab the info I need from external lookup tables.

Can you provide any clarity?

**Comment by ldecicco-USGS** [comment]
We did a pretty extensive update to that function which made it a lot more flexible and useful...and now that you mention it...we did lose that parameter_cd "join".... 

I can add that back in for the next update, in the meantime, if you'd like, you can add:

```r
library(dataRetrieval)
library(dplyr)
library(dplyr)
availableData <- whatNWISdata(siteNumber = '05114000') %>%
  left_join(parameterCdFile, by=c("parm_cd"="parameter_cd"))
```

**Comment by jasmyace** [comment]
Ok, just wanted to make sure I understood the behavior.  

Thanks!
