### ISSUE TITLE
getADAPSData failing at constructNWISURL

### ISSUE THREAD

**Issue by crachol** [USGS-R/dataRetrieval#404]
There appears to have been a change to NWIS web/web services where R is getting hung-up while trying to pull data. We double-checked web services and that appears to be working just fine for the sites we're interested in. Can this please be double-checked?

**Comment by ldecicco-USGS** [comment]
Is this for historical (older than 120 days) "instantaneous" data? Or some other data? I'm looking into the problem now, and currently seeing the issue only for that type of data.

**Comment by crachol** [comment]
This is for current data (within the past 2 weeks). I successfully ran the script last Wednesday, but am having issues with it today.

**Comment by crachol** [comment]
It looks like it's working again -- saw the issue reported by wliu2016 and that the servers were restarted.

**Comment by ldecicco-USGS** [comment]
Great, was just going to ask if you were still having problems.
