### ISSUE TITLE
HTTP 502 error

### ISSUE THREAD

**Issue by wliu2016** [USGS-R/dataRetrieval#405]
This morning, it appears that the website is temporally not responding in USGS.  I tried to pull data using readNWISuv  but it keeps failing, giving me a HTTP 502 error.  Attached below:

> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /nwis/iv/.
> 
> Reason: Error reading from remote server

I checked the data portal in USGS website and it works, so maybe there is something wrong with the website that dataRetrival tries to pull data from?

Thanks,
Wenlong

**Comment by ldecicco-USGS** [comment]
They just restarted a server, so it should be working again. Let me know if you still are seeing 502's.

**Comment by wliu2016** [comment]
It works, thanks for your quick response!

Cheers~
Wenlong

**Comment by smille86** [comment]
I'm seeing 502's again when using readNWISuv this morning.  Is the server down again? 
Thanks,
Sam

**Comment by ldecicco-USGS** [comment]
Yup! I informed them and they restarted the server. AND....they are now seriously working on trying to figure out what's suddenly clonking out the server (I'm sure that's the technical word).

**Comment by smille86** [comment]
All working again,
Thanks!
