### ISSUE TITLE
Cross border data integration

### ISSUE THREAD

**Issue by boshek** [USGS-R/dataRetrieval#421]
Hello,

I am the maintainer of the [tidyhydat](https://github.com/ropensci/tidyhydat/tree/master/R) package which does approximately the same thing as `dataRetrieval` but only for Canadian hydrometric data. Because rivers flow across borders, I've been thinking that it would be useful to have a function in `tidyhydat` that munges the USGS data into WSC formats and vice versa to facilitate combining the data for any cross-border hydrological analysis. A lovely side benefit for Canadian users is that our hydrometric data will then integrate seamlessly with tools like EGRET (I think).  I think the API would be two functions:

```
wsc_to_usgs()
```
and
```
usgs_to_wsc()
```
or something like that. I'm curious if you folks have ever thought about something like this and whether you see enough value in this to share these functions (assuming we can get it working properly) across the two packages (import package and re-exported functions). I plan to implement this for `tidyhydat` anyways because it is likely valuable for our purposes but before I went too far down this road, I wanted to reach out here.

**Comment by ldecicco-USGS** [comment]
Cool idea! I'd be happy to help get the Canadian data into an EGRET object. That might be easier than declaring some "usgs" format (because, depending on the service we're using, it can be different). 

I need to work on some `dataRetrieval` updates in the next couple weeks, nothing earth shattering, but to start, I could add `tidyhat` to the package "Suggestions".

I think we'll both be a the "rOpenSci" conference, let's chat about the best way to do this!

**Comment by ksonda** [comment]
I realize this is super old but possibly could be revived, perhaps piloting using SensorThings API as a common upstream interface, at least between USGS IV Service and NRCan GIN when they both are up? @jkreft-usgs

**Comment by dblodgett-usgs** [comment]
I like this idea. I'd be happy to support some pilot implementation if I can.

**Comment by boshek** [comment]
Looks like someone DIY'ed this and used tidyhydat and EGRET together: https://iopscience.iop.org/article/10.1088/1748-9326/ac1817/pdf

**Comment by ldecicco-USGS** [comment]
Awesome!
