### ISSUE TITLE
readNWISgwl lev_dateTimes returns NA for dates/times already in UTC

### ISSUE THREAD

**Issue by cpenn-usgs** [USGS-R/dataRetrieval#431]
If the returned `lev_tz_cd_reported` is already in UTC, `lev_dateTime` is returned as `NA`.
Example:

`
GWL <- readNWISgwl(siteNumbers = '393227104343401', startDate = '2015-04-02')
`
`
GWL2 <- readNWISdata(service='gwlevels', site = '393227104343401', startDate='2015-04-02')
`
There was a similar issue in WQ-Review, probably because UTC is not used very often when recording measurements/collecting samples. UTC just had to be added to the offset table. Might be a similar fix for how `dataRetrieval` handles the conversion of the date `lev_dt` and and `lev_tm` to `lev_dateTime`.

**Comment by ldecicco-USGS** [comment]
Hmmm....I'll have a look, thanks for creating the issue!
