### ISSUE TITLE
readNWISdv not returning site data 

### ISSUE THREAD

**Issue by lerban** [USGS-R/dataRetrieval#433]
Having a strange issue re-running code.  I previously retrieved daily discharges for a group of stream gages, but today one returns no data.  I can still plot the data, using NWIS web, that should be returned by:

> q <- readNWISdv('03341500', '00060', '2015-01-01', '2015-12-31')
> q
data frame with 0 columns and 0 rows

Re-running for a different gage returns data as expected.

**Comment by wdwatkins** [comment]
Can you run `setAccess('cooperator')`, and then try that command again?

**Comment by lerban** [comment]
Ran it, but result is the same

**Comment by wdwatkins** [comment]
Are you on the same network that you can see the data through NWIS web? 

 It seems this site's data is not publicly available.  NWIS web will automatically give you access if you are on an internal network, but you have to use `setAccess` manually when using the web services.  So if you are on the same network and have the access level set to the right level, dataRetrieval should give you the same data as NWIS web.  If that isn't the case, we can investigate further on our end.

**Comment by ldecicco-USGS** [comment]
I'm sending an email to an NWIS contact to find out why that site switched over to a more restricted access. Can you see daily data options here:

https://waterdata.usgs.gov/nwis/inventory/?site_no=03341500&agency_cd=USGS

?

**Comment by lerban** [comment]
Yes, can get to the daily data through that link.  I'm not on a USGS network.  

Adding to the story is that a year ago I used dataRetrieval to pull discharge data for this gage back to 1928.  Now I can't get any, and the NWIS web link above only reports discharge data availability back to 2007.

Thanks for looking into it.  Not an urgent matter for me, but I'm troubled by changing historical data access with gage and time.

**Comment by ldecicco-USGS** [comment]
I got a response:
"The gage moved earlier this year so we had changed some computations to reduced web access until they were confirmed valid at the new location. It looks like the daily values were accidentally not updated to public access after that confirmation.  I have corrected that on the web settings.  Thanks!"

**Comment by hquintal16** [comment]
Hi, I'm running into the same issue with the gage 360143078540945. Any chance this can be remedied?

**Comment by ldecicco-USGS** [comment]
I'd first run 'whatNWISdata' to see what data is available from that site:
```r
what_data <- whatNWISdata(siteNumber = "360143078540945")

what_data[,c("data_type_cd", "parm_cd", "stat_cd")]
  data_type_cd parm_cd stat_cd
1           ad    <NA>    <NA>
2           dv   00045   00006
3           uv   00045    <NA>
```

So from that, if you were going to use the `readNWISdv` function, the only options you have are parameter code 00045 and stat_cd 00006. The default stat_cd is 00003, so unless you specify it, you won't get data:

```r
rain_data <- readNWISdv(siteNumbers = "360143078540945",
                        parameterCd = "00045",
                        statCd = "00006")
nrow(rain_data)
[1] 5452
```

I had to look up what 00006 is, it's "SUMMATION VALUES":
https://help.waterdata.usgs.gov/stat_code
