### ISSUE TITLE
dead link for stats codes in readNWISuv doc

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#437]
A list of statistic codes can be found here: [https://nwis.waterdata.usgs.gov/nwis/help/?read_file=stat&format=table](https://nwis.waterdata.usgs.gov/nwis/help/?read_file=stat&format=table). yields: 
> The program name that you tried to access is not recognized.The valid program names available in the NwisWeb system include:

**Comment by ldecicco-USGS** [comment]
Sigh, those help pages ! I'll look for where it might have been moved.

**Comment by jread-usgs** [comment]
Is it here? https://help.waterdata.usgs.gov/stat_code See #438 issue which is kind of linked to this one.

**Comment by ldecicco-USGS** [comment]
Yup, just responded over there. the "help.waterdata" is (was?) prone to frequent failure. I had to remove all those links because I was getting constant "WARNINGS" from CRAN. I'll ask the NWIS crew if it's on a more stable server these days...maybe we can put those back in. They are so useful

**Comment by ldecicco-USGS** [comment]
Links seem back online.
