### ISSUE TITLE
readNWISstat not providing latest statistics

### ISSUE THREAD

**Issue by UserFeb2016** [USGS-R/dataRetrieval#440]
Hi - I am using readNWISstat to retrieve monthly means for a few sites. It seems the monthly means are available only until March 2018 (site - 02310280). How often are these statistics updated? Any help is greatly appreciated.

Thanks

**Comment by ldecicco-USGS** [comment]
Good question...I'll ask around.

**Comment by ldecicco-USGS** [comment]
I asked...and then forgot to respond here! So, the stats are only calculated once the data is "Approved". The data for that site after April 4th is not yet Approved (still in "Provisional" status if you go to the "dv" service), so the stats are not updated. It depends on individual sites/resources to approve the data...I can't tell you when that site in particular will get updated. Make sense?

**Comment by UserFeb2016** [comment]
Thank you for your response. So I am wondering that when I go to https://waterwatch.usgs.gov/?m=real&r=fl , if the percentile value in the pop-up (which appears when I hover the cursor over the site marker) is calculated from both approved and provisional data or just approved data? Also, is there a way to retrieve the percentiles? Thank you.
