### ISSUE TITLE
Allow for sending a custom user agent string

### ISSUE THREAD

**Issue by jkreft-usgs** [USGS-R/dataRetrieval#442]
As a developer of a downstream application that uses dataRetrieval, I want to be able to add additional information to the downstream service call via the user agent headers, so that it is eventually possible to see how much my application is using various web service endpoints by using the analytics for those services

**Comment by ldecicco-USGS** [comment]
So we don't need to add an argument in all of the functions....I'm working on adding this:
```r
default_ua <- function() {
  versions <- c(
    libcurl = curl::curl_version()$version,
    httr = as.character(packageVersion("httr")),
    dataRetrieval = as.character(packageVersion("dataRetrieval"))
  )
  
  ua <- paste0(names(versions), "/", versions, collapse = " ")
  
  if("UA.dataRetrieval" %in% names(options)){
    ua <- paste0(ua, "/", options()[["UA.dataRetrieval"]])
  }
    
  return(ua)
}
```
so a user (or application) could set an option to add a suffix to the standard UA. 2 questions I guess:
1. Does anyone care if it's a prefix or suffix? 
2. Does anyone have a preference on the option name? 
```r
options(UA.dataRetrieval = "Fancy new shiny app1")
```
