### ISSUE TITLE
readWQPdata error with different siteid

### ISSUE THREAD

**Issue by ewiggans** [USGS-R/dataRetrieval#447]
When trying to assign a variable to known site name meeting previously screened parameters, the following error occurs (site is located in the South River in Maryland near Annapolis):

site1 <- readWQPdata(siteid = "CBP_WQX-WT8.1")
Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)

However, the same syntax works perfectly fine for the following site (which appears to be geographically in the same location...): 
site2 <- readWQPdata(siteid = "MDDNR-WT8.1")

_Both_ lines work fine for my colleague, but not for me, where I get the error for Site 1. We're using the same version of R, 3.5.1, and the same version of dataRetrival, 2.7.3. I suspect it may be related to the issue here: https://github.com/USGS-R/dataRetrieval/issues/428 but that does not explain why it's working for others and not me. When specifying a larger area to grab individual sites from, both of these sites appear individually within a larger group, and then by pairing down the query we were left with these two, so they do appear to be different within the larger database.

**Comment by jsta** [comment]
I was able to get your example to run after making changes in the above linked PR. The error is caused by the fact that there are `ActivityStartTime/TimeZoneCode` values but no `ActivityEndTime/TimeZoneCode` values:

```r
unique(site1$ActivityStartTime.TimeZoneCode)
[1] "EST" NA   

unique(site1$ActivityEndTime.TimeZoneCode)
> [1] NA
```
