### ISSUE TITLE
update ubuntu version used on travis

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/dataRetrieval#450]
https://github.com/USGS-R/dataRetrieval/blob/master/.travis.yml#L9

`trusty tahr` is end-of-life in 2019, should probably jump to the current LTS distribution `bionic beaver` (I assume the field would be `bionic`?)

In case you were also wondering what a tahr is 😄 🐴 : https://www.google.com/search?q=tahr&rlz=1C5CHFA_enUS695US695&oq=tahr&aqs=chrome..69i57j0l5.512j0j7&sourceid=chrome&ie=UTF-8

**Comment by ldecicco-USGS** [comment]
I could probably plop that in right now while I'm trying to get these pesky tests to pass.... and here I always assumed `trusty` meant...I could trust it 🤦‍♀️

**Comment by ldecicco-USGS** [comment]
Done
