### ISSUE TITLE
unexpected return with readNWISqw

### ISSUE THREAD

**Issue by jaywt** [USGS-R/dataRetrieval#451]
## Platform: 
have reproduced this error/output on both Windows (windows 7 and R 3.5.1 and dataretrieval 2.7.3) and Linux (OSGeoLive 12.0 R 3.4.4 and dataretrieval 2.7.3)

### 2.2 Returned data frame not empty and it contains result values with parm_Cd=00930 as expected

What might be the explanation? Did I do anything wrong when I specified parameterCd as '00930'? Thank you.

**Comment by ldecicco-USGS** [comment]
Yeah, just in the last couple of days I've realized there's a bug in the `readr` package. I've reported it and they've fixed the bug....but it's not out on CRAN yet. In the meantime, you can install `readr` like this:

```r
devtools::install_github("tidyverse/readr")
```

You'll need to make sure `readr` is NOT loaded when you do the `install_github` installation. 

Let me know if you are still having problems.

**Comment by jaywt** [comment]
> Yeah, just in the last couple of days I've realized there's a bug in the `readr` package. I've reported it and they've fixed the bug....but it's not out on CRAN yet. In the meantime, you can install `readr` like this:
> 
> ```r
> devtools::install_github("tidyverse/readr")
> ```
> 
> You'll need to make sure `readr` is NOT loaded when you do the `install_github` installation.
> 
> Let me know if you are still having problems.

Installing development version of readr (Version: 1.3.0.9000) solved the problem. Thanks, Laura.
