### ISSUE TITLE
readNWISuv not recognizing p-code 95202

### ISSUE THREAD

**Issue by ostoken** [USGS-R/dataRetrieval#452]
I've tried to run the readNWISuv command for p-code 95202 (cyanobacteria/blue green algae), but I'm getting zero data returned for time periods that I know have data in Aquarius. I can pull in other p-codes but for some reason the dataRetrieval package does not seem to recognize 95202. Is this happening for a reason?

**Comment by ldecicco-USGS** [comment]
Can you give me an example `readNWISuv` call? (ie..a site/time that you know exists)

**Comment by ostoken** [comment]
This is the code I was running. It works for other parameters at the site such as dissolved oxygen (00300).

siteNumber <- '422305121553803'
parameterCd <- '95202'
startDate <- "2015-05-20"
endDate <- "2015-10-20"
tz <- "America/Los_Angeles"

Data <- readNWISuv(siteNumber,parameterCd,startDate,endDate,tz)
Data <- renameNWISColumns(Data)

**Comment by ldecicco-USGS** [comment]
Apparently the data in Aquarius is set to Provisional... and the "uv" service won't publish provisional data that is older than 3 years. The data before 2015 is set to Approved and the data after 2015 is also provisional but within the 3 year window.

So....that's the reason. If you know who manages that data, you could ask them if there's any chance that data will be tagged as "Approved"...but off-hand I don't know that process for that particular type of data.

**Comment by ostoken** [comment]
I didn't realize there was a time limit for the uv data. Thanks for catching that for me!

**Comment by ldecicco-USGS** [comment]
only a time limit for provisional data!
