### ISSUE TITLE
readWQPdata error

### ISSUE THREAD

**Issue by jjwill2** [USGS-R/dataRetrieval#455]
Trying to query data for a specific siteid yielded an error. I have confirmed this siteid is in WQP. This appears similar to issues in #447 (now closed). For data activities attached to this siteid, there are 'ActivityStartDate', ActivityStartTime/Time', and 'ActivityStartTime/TimeZoneCode' values, but no 'ActivityEndDate', ActivityEndTime/Time', or 'ActivityEndTime/TimeZoneCode' values. The fix for #447 apparently did not address this type of case?

hctest <-readWQPdata(siteid = "IDEQ_WQX-2018LEWHC67_03")

Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)

**Comment by ldecicco-USGS** [comment]
Do you have the github version installed? I think #449 fixed the issue. Try:

```r
devtools::install_github("USGS-R/dataRetrieval")
```
Also...it's never a bad idea to update ALL of your packages:

![update](https://user-images.githubusercontent.com/1105215/54784476-03d57380-4bf2-11e9-9537-6aa6ac4ba46c.png)

If you've done both these things and are still having the problem, let me know and paste the results of running:
```r
devtools::session_info()
```
I do hope to send the fix up to CRAN soon....maybe next week?

**Comment by ldecicco-USGS** [comment]
Fix is on it's way to CRAN
