### ISSUE TITLE
readWQPdata error activityendtime/timezonecode

### ISSUE THREAD

**Issue by judithcthomas** [USGS-R/dataRetrieval#456]
I am having a problem with the readWQPdata that I have not previously had. 
When I run the following line of code
>BactData <- readWQPdata(statecode="08",huc="14010005", characteristicName="Escherichia coli")

I get the following error.
Error: Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)

**Comment by pinshuai** [comment]
I got the same error when pulling data using `readWQPdata`:

    `qwData <- readWQPdata(bBox = c(-76.6,38.3,-74.0,42.6),  characteristicName="Phosphorus", startDate=startDate)`

But if I changed `bBox` to `statecode = 'NJ'`, it works fine. I suspect some sites gave a logical output for `ActivityEndTime.TimeZoneCode`.

**Comment by ldecicco-USGS** [comment]
Do you have the github version installed? I think #449 fixed the issue. Try:

```r
devtools::install_github("USGS-R/dataRetrieval")
```
Also...it's never a bad idea to update ALL of your packages:

![update](https://user-images.githubusercontent.com/1105215/54784476-03d57380-4bf2-11e9-9537-6aa6ac4ba46c.png)

If you've done both these things and are still having the problem, let me know and paste the results of running:
```r
devtools::session_info()
```
I do hope to send the fix up to CRAN soon....maybe next week?

**Comment by ldecicco-USGS** [comment]
The fix is on it's way to CRAN
