### ISSUE TITLE
Max limit of HUC list

### ISSUE THREAD

**Issue by pinshuai** [USGS-R/dataRetrieval#457]
When I query more than 10 HUC using `readNWISdata` I got the following error:

```
Error in getWebServiceData(obs_url, encoding = "gzip"): HTTP Status 400 - Minor HUC list size exceeded at list position 10 [maxMinorHucLimit=[10]]`

Traceback:
1. readNWISdata(huc = HUCcode, parameterCd = pCode, service = "site", asDateTime = TRUE, seriesCatalogOutput = TRUE)
2. importRDB1(baseURL, tz = tz, asDateTime = asDateTime, convertType = convertType)
3. getWebServiceData(obs_url, encoding = "gzip")
4. stop(statusMsg)
```

The HUC list I used is:
`HUC = c("02040201","02040202", "02040203", "02040204","02040205", 
            "02040206", "02040207", "02040101","02040102", "02040103", 
            "02040104","02040105", "02040106")`

How should I bypass this upper limit for HUC?

**Comment by wdwatkins** [comment]
That limit is part of the water services API that dataRetrieval uses.  You'll need to loop over your HUCs in groups of 10, something like this:
```

**Comment by pinshuai** [comment]
Thanks. That's very helpful.
