### ISSUE TITLE
vignette is difficult to read in RStudio in dark mode

### ISSUE THREAD

**Issue by ethankale** [USGS-R/dataRetrieval#460]
When running the vignette `vignette("dataRetrieval", package="dataRetrieval")`, if RStudio is in dark mode most of the code examples are really difficult to parse because they default to white-on-white text.
![dataRetrieval vignette](https://user-images.githubusercontent.com/5944383/55263913-d612af00-522f-11e9-8814-6cc1c9d32cb5.PNG)

**Comment by ldecicco-USGS** [comment]
Hmm, other than the vanilla styling, there is a `highlight=TRUE` option in the knitr options. I'll see what happens when I remove that (it's an artifact from the `sweave` LaTeX days). In the meantime, you can go here:

http://usgs-r.github.io/dataRetrieval/articles/dataRetrieval.html

I'm hoping to improve that overall `pkgdown` site in the future.

**Comment by ethankale** [comment]
Cool, thanks.  I've been highlighting the text in RStudio to read it, that works too.  It's also an issue for the every-other coloring in the tables, FWIW.

**Comment by ldecicco-USGS** [comment]
Specifically what " dark mode " are you using? I turned off the highlighting and want to see how it looks before I push it up.

**Comment by ldecicco-USGS** [comment]
I dug into this a bit and I think it's just something we'll have to live with. If you click the "pop out" button:

![image](https://user-images.githubusercontent.com/1105215/55637240-305cc400-578a-11e9-9ffb-e27313c8f87d.png)

You get the vignette in the original style (in which the code shows up just fine). Looking at RStudio's github:

https://github.com/rstudio/rstudio/issues/3175

I think that is basically their solution (not rendering various styles on the popped out vignettes).
