### ISSUE TITLE
NGWMN timing out

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#466]
Between yesterday and today we can't seem to complete a few of the NGWMN examples/tests. I've commented them out so that the other fixes can run.

I'll try to find out if the service itself has changed (using URLs are taking forever in the browser as well as via dataRetrieval). 

Whether or not it's the service's problem or dataRetrieval, we'll need to add these tests/examples back in.

**Comment by wdwatkins** [comment]
I suspect the issue is the WML2 parsing.  Do you know if this just started since we changed things late this week?  Possibly with my PR?

**Comment by ldecicco-USGS** [comment]
It was the day after the merge ....BUT.... that happens to also be the day after a major upgrade on the services. So, we need to investigate both sides of the coin.

**Comment by ldecicco-USGS** [comment]
Let's not forget : "In the event that the NGWMN slowdown is a parsing issue, can we have a test that fails after a certain time if something doesn't complete?"
