### ISSUE TITLE
querying by ProjectIdentifier is much slower than by site for same data (readWQPdata)

### ISSUE THREAD

**Issue by jjwill2** [USGS-R/dataRetrieval#470]
Using readWQPdata, querying data by ProjectIdentifier is far slower than querying the same data by a list of siteids. Querying by ProjectIdentifier is a primary way I need to interact with WQP data, but is so slow that it is not really usable.

`
# query data using list of sites for ProjectIdentifier 'IDEQ LEW HC' (fast)
sites <-c("IDEQ_WQX-2018LEWHC67_03", "IDEQ_WQX-2018LEWHC67_02", "IDEQ_WQX-2018LEWHCSP", "IDEQ_WQX-2018LEWHCLO")
bysite_start <-Sys.time()
bysite <-readWQPdata(siteid = sites)
bysite_end <-Sys.time()
bysite_end-bysite_start

# query same data by ProjectIdentifier (slow)
byproject_start <-Sys.time()
byproject <-readWQPdata(ProjectIdentifier = "IDEQ LEW HC")
byproject_end <-Sys.time()
byproject_end-byproject_start`

**Comment by jkreft-usgs** [comment]
You might try adding an organization ID to your query- that should significantly narrow the scope of the query, which is otherwise scanning the entire table for a project identifier.
