### ISSUE TITLE
readWQPdata join error...site has a slash

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#472]
readWQPdata(siteid = 'MDNR-5006/0.7', characteristicName = 'Temperature, water')
Error: Can't join on 'code' x 'ActivityStartTime/TimeZoneCode' because of incompatible types (character / logical)

**Comment by limnoliver** [comment]
Just wanted to note that not all sites with a slash give the same error. The below fails -- and also fails on the web portal map (even though it auto-completes as a recognized site name). 

```
readWQPdata(siteid = 'COE/ISU_WQX-17630001', characteristicName = 'Temperature, water')
Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 2.2 seconds...
```

![image](https://user-images.githubusercontent.com/15788176/56506556-7f259000-64e4-11e9-8eac-f3d32b773add.png)

**Comment by ldecicco-USGS** [comment]
Yeah, I think the joining issue is pretty trivial to fix (the current PR should do that). I still think the `POST` should be explored though....
