### ISSUE TITLE
Add a verbose option to notify when different parts of call finish 

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/dataRetrieval#478]
I had this implemented for a while with NGWMN functions when there were issues, it can be useful for debugging.  Basically, print messages when key steps complete, such as contacting the server, finishing a download, and finishing parsing.  Then if a call is taking forever you know what is step it is stuck on.  Would probably want the argument to default to false.   

Could also be passed into `httr` to give more detailed information on the web service call.

**Comment by ldecicco-USGS** [comment]
Yeah, what you can see for now is described here:
https://owi.usgs.gov/R/dataRetrieval.html#33

basically add:
```r
library(httr)
set_config(verbose())
set_config(progress())
```
to the top of your script
