### ISSUE TITLE
duplicate parameters different period of record

### ISSUE THREAD

**Issue by jmmms** [USGS-R/dataRetrieval#481]
How can I specifiy which parameter to download when there are two existing records with the same parameter? See the screen shot of the NWIS website attached. The readNWISsite function returns the shorter record ending 2017-09-30 but I would like to download the most recent data.

Thank you.

![sampleofissue](https://user-images.githubusercontent.com/50849001/58054904-590e0280-7b19-11e9-882b-32135c382e96.JPG)

**Comment by ldecicco-USGS** [comment]
If you run:
```r
site <- "10109001"
x <- readNWISdv(site,"00060")
```
you'll see 2 value columns, and 2 remark code columns:
```r
names(x)
[1] "agency_cd"              "site_no"               
[3] "Date"                   "X_..2.._00060_00003"   
[5] "X_..2.._00060_00003_cd" "X_00060_00003"         
[7] "X_00060_00003_cd" 

range(x$Date)
[1] "1921-10-01" "2019-05-19"

```
The column "X_..2.._00060_00003" ends at the end of WY2017, the column "X_00060_00003" goes to today.

So, to answer your question, you can't specify a certain column, but you are getting both, and you can filter out the one you don't want. Sound good?

**Comment by jmmms** [comment]
Wow, you are quick. Yes, thank you that explains it. To be clear, is it always the case that the discontinued is given some other name and the most current retains the "X_00060_00003" column name?

**Comment by ldecicco-USGS** [comment]
I think you are correct....but there might be conditions that I'm not aware that would make that not true. For example, if there's a parameter that's measured twice at the same location (and both are still active), you'd need look at the column headers and figure out what's what (sometimes they are more descriptive that "..2"). For instance, I know there are some sites that have 2 turbidity sensors, 1 aimed upstream and 1 downstream...from the column header you could figure out which is which. 

Also...if a parameter was discontinued, and not replaced...the historical data would still by default have the "X_00060_00003" column header.

**Comment by jmmms** [comment]
I understand. Thank you very much for the quick and thorough reply. Have a nice day.
