### ISSUE TITLE
Leading zeros in stateCd get dropped in whatNWISdata

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/dataRetrieval#482]
`whatNWISdata` fails with a `HTTP Status 400 - countyCd: invalid fips5 county code string argument length` error when used with `stateCd` and `countyCd`.

This call fails:
```
Tulare_As <- whatNWISdata(stateCd="CA",countyCd="Tulare",siteType="GW",parameterCd="01000")
```
Because it translates CA to "6" instead of "06", 
https://waterservices.usgs.gov/nwis/site/?seriesCatalogOutput=true&countyCd=6113&siteType=GW&format=rdb

This happens for all state codes < 10.  Not sure if other functions are affected by this too.  Presumably state codes just need to be handled as char instead of numeric somewhere.

For now, it will work if you specify an explicit 5-digit county FIPs code, **without** the state:
`Tulare_As <- whatNWISdata(countyCd="06107",siteType="GW",parameterCd="01000")`

**Comment by lydiableifuss** [comment]
Hello! I am not sure, but I am wondering if the problem I am having is in this same vein? 

When I try to pull all gw levels by state, not all levels populate, and I have tried this for several states. I am working to gather all gw levels and have pulled the site information for all GW sites in each state. However, when I call:

wy_dtw <- readNWISdata(stateCd="WY, service="gwlevels")
OR
wy_dtw <- readNWISdata(stateCd="Wyoming", service="gwlevels")

only 10,814 measurements populate. I cross checked how many measurements there should be by running the NWIS gwlevels url for WY and there should be 64,386 measurements (url below).

Any advice would be so greatly appreciated! - Thank you
 
(https://nwis.waterdata.usgs.gov/nwis/gwlevels?state_cd=wy&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&format=rdb&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=state_cd)
