### ISSUE TITLE
trying to get daily values for site numbers using readNWISdv error

### ISSUE THREAD

**Issue by deleteblue** [USGS-R/dataRetrieval#489]
I'm trying to get daily values 
<- readNWISdv( siteNumbers = sitenumbers) 
I keep getting this error (the numbers are the sites in site numbers).

For: https://waterservices.usgs.gov/nwis/dv/?site=11516530,11516900,11517000,11517500,11519500,11520500,11521500,11522500,11523000,11523200,11525500,11525530,11525600,11525630,11525655,11525670,11525854,11526250,11526400,11526500,11527000,11528500,11528700,11530000,11530500,11532500&format=waterml,1.1&ParameterCd=00060&StatCd=00003&startDT=1851-01-01

Error in getWebServiceData(obs_url, encoding = "gzip") : 
  Gateway Timeout (HTTP 504).

What could possibly be the problem?

**Comment by wdwatkins** [comment]
How many sites are you requesting at once?  We generally recommend chunking large requests into groups of 200.  

A 504 error code suggests that the web service just isn't responding to your request in a timely manner, so this is an issue with the NWIS web services that dataRetrieval utilizes, not the package itself.  I would imagine it just takes a long time to retrieve data for this many sites at once for the entire ~160 years.  You might have better luck breaking this request up into a few smaller pieces, and then appending the results.

**Comment by deleteblue** [comment]
Thank you. Yeah that was the problem I think because I was requesting too many sites at once. I'll try splitting them and then pasting together.
