### ISSUE TITLE
Downloaded lat/long coordinate datum don't match web service?

### ISSUE THREAD

**Issue by globalwatergeek** [USGS-R/dataRetrieval#498]
When comparing location information for site numbers in Minnesota, the lat/long datum are different between those downloaded from dataRetrieval and the web interface. The [web service shows mostly NAD27 datum](https://waterdata.usgs.gov/nwis/inventory?multiple_site_no=04010500%2C04012500%2C04014500%2C04015330%2C04015500%2C04016000%2C04016500%2C04017000%2C04018750%2C04019000%2C04019300%2C04019500%2C04024000%2C04024098%2C05030000%2C05030500%2C05040500%2C05046000%2C05049000%2C05051300%2C05061000%2C05061500%2C05062000%2C05062500%2C05064000%2C05067500%2C05068000%2C05068500%2C05069000%2C05074500%2C05075000%2C05076000%2C05076500%2C05077700%2C05078000%2C05078230%2C05078500%2C05079000%2C05080000%2C05083500%2C05087500%2C05093000%2C05094000%2C05095000%2C05096000%2C05096500%2C05104000%2C05104500%2C05106000%2C05107000%2C05107500%2C05112000%2C05124480%2C05124500%2C05125000%2C05126000%2C05126210%2C05126500%2C05127000%2C05127500%2C05128500%2C05129000%2C05129115%2C05129290%2C05130500%2C05131000%2C05131500%2C05132000%2C05133500%2C05134200%2C05139500%2C05140000%2C05140500%2C05200510%2C05211000%2C05212700%2C05216860%2C05217000%2C05220500%2C05227500%2C05241500%2C05242300%2C05242700%2C05243725%2C05244000%2C05244500%2C05245100%2C05245500%2C05247500%2C05267000%2C05270500%2C05270700%2C05274700%2C05275000%2C05275500%2C05278000%2C05278500%2C05279000%2C05280000%2C05283500%2C05286000%2C05287890%2C05288500%2C05288705%2C05292000%2C05292500%2C05293000%2C05294000%2C05300000%2C05301000%2C05304500%2C05305000%2C05311000%2C05311400%2C05313500%2C05315000%2C05316500%2C05316580%2C05317000%2C05317200%2C05318000%2C05319500%2C05320000%2C05320270%2C05320500%2C05325000%2C05327000%2C05330000%2C05330920%2C05331000%2C05331001%2C05331580%2C05336700%2C05337400%2C05338500%2C05339500%2C05340000%2C05340050%2C05344981%2C05345000%2C05345100%2C05346000%2C05353800%2C05355200%2C05355250%2C05372995%2C05373000%2C05374000%2C05374500%2C05374900%2C05376000%2C05376500%2C05376800%2C05377500%2C05378300%2C05378500%2C05379000%2C05383950%2C05384000%2C05384500%2C05385000%2C05385500%2C05386000%2C05457000%2C05476000&group_key=NONE&format=sitefile_output&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=dec_lat_va&column_name=dec_long_va&column_name=coord_datum_cd&column_name=alt_va&column_name=alt_datum_cd&list_of_search_criteria=multiple_site_no). However, the same site numbers from dataRetrieval show exclusively NAD83. See [nwis_waterdata_MN.csv.zip](https://github.com/USGS-R/dataRetrieval/files/3774821/nwis_waterdata_MN.csv.zip) Thanks for any guidance you can offer.

**Comment by ldecicco-USGS** [comment]
Looks like a bug in the "web service" link to me. The web services that dataRetrieval looks at look like this:
https://waterservices.usgs.gov/nwis/site/?siteOutput=Expanded&format=rdb&site=05114000

The "dec_lat_va" (and long) have the "dec_coord_datum_cd -- Decimal Latitude-longitude datum" of NAD83. The lat_va/long_va go with the "coord_datum_cd  -- Latitude-longitude datum", which is NAD27. 

Individual site pages look OK:
https://waterdata.usgs.gov/nwis/inventory/?site_no=04010500
Latitude 48°00'44",   Longitude 89°36'58"   NAD27

But that list from a state query does look like it's putting out the wrong datum to me.  I'll go talk to the folks that make that page and see what they say.

**Comment by ldecicco-USGS** [comment]
How are you generating the "web service" link? I pulled out all but one of the sites and it looks like this:

https://waterdata.usgs.gov/nwis/inventory?multiple_site_no=04010500&group_key=NONE&format=sitefile_output&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=dec_lat_va&column_name=dec_long_va&column_name=coord_datum_cd&column_name=alt_va&column_name=alt_datum_cd&list_of_search_criteria=multiple_site_no

If you want the decimal lat/longs, then the coord_datum_cd should be changed to dec_coord_datum_cd.

https://waterdata.usgs.gov/nwis/inventory?multiple_site_no=04010500&group_key=NONE&format=sitefile_output&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=dec_lat_va&column_name=dec_long_va&column_name=dec_coord_datum_cd&column_name=alt_va&column_name=alt_datum_cd&list_of_search_criteria=multiple_site_no

**Comment by globalwatergeek** [comment]
You're right -- I was pulling the wrong column from the web platform. Thanks for the clarification. dataRetrieval is a lot easier to use!
