### ISSUE TITLE
using statistic code in readNWISuv

### ISSUE THREAD

**Issue by deleteblue** [USGS-R/dataRetrieval#499]
Is there a way to get the daily average, or use statistic code="00003" using readNWISuv? Because in the data we are looking for, only current condition is being recorded.

**Comment by ldecicco-USGS** [comment]
You can use the `readNWISdv` function! The "uv" service doesn't have daily values, but the "dv" service is specifically for that. `?readNWISdv` for more info and let me know if you have questions beyond that.

**Comment by deleteblue** [comment]
I used readNWISdv but for the sites that I need I do not get any data. It returns zero rows zero columns. It seems that they only have the current condition. So I need to get the daily average before downloading, because downloading all current conditions would require a large amount of storage and takes a long time.

**Comment by ldecicco-USGS** [comment]
Ah, OK. What sites are you looking at? Sometimes the data managers have mistakenly not pushed out the data to the dv service, other times there's a legitimate reason it's not there.

**Comment by deleteblue** [comment]
I am looking for sites in California and want to get daily values for gage height and precipitation.

**Comment by ldecicco-USGS** [comment]
I guess for precip they don't typically use the daily mean "00003", they use "00006" (sum of the day).  So:
```
CA <- whatNWISdata(stateCd = "CA",
                   service = "dv",
                   statCd = c("00003","00006"),
                   parameterCd = c("00065","00045"))
nrow(CA)
[1] 86
```
Not a ton of sites...and it's all precip, no gage height.


As for the gage height, it's up to the CA Data Chief to decide what data gets pushed out to the "dv" service. I just played around a bit, it does seem like Wisconsin for instance pushes out their gage height to the daily value service, but CA does not (there are a lot of California discharge daily values...not sure if that's possible for your analysis...)

So....if you want to ask around the CA WSC to find out who is the "data chief" that's the person that can let you know why or why not they push their data to the daily service.

**Comment by deleteblue** [comment]
Thank you so much.
