### ISSUE TITLE
Add package functionality/examples to README

### ISSUE THREAD

**Issue by TrashBirdEcology** [USGS-R/dataRetrieval#500]
Add basic functionality examples or a 'quickstart' guide to the README.

**Comment by ldecicco-USGS** [comment]
I'll probably get some time in spring to update the dataRetrieval repo to follow more modern rOpenSci/pkgdown documentation recommendations. In the meantime, you can check out:

http://usgs-r.github.io/dataRetrieval/articles/dataRetrieval.html
or
https://owi.usgs.gov/R/dataRetrieval.html#1

**Comment by TrashBirdEcology** [comment]
Yeah, this resource is great but is not on any landing pages, and is
currently filed under "background" on your .io.

Not complaining whatsoever, just letting you know my experience in clicking
around :)
