### ISSUE TITLE
Pulling gw levels by state, readNWISdata not pulling all measurements? 

### ISSUE THREAD

**Issue by lydiableifuss** [USGS-R/dataRetrieval#516]
Hello! 

Background: I am working to gather all gw levels for the 17 western contiguous states, hoping to join the site info (lat and long) with the depth to water/level measurements for each site. I have pulled the site information for all GW sites in each of these states. 

Issue: When I try to pull all gw levels by state, it appears that not all levels/measurements populate, and I have tried this for several states. 

When I run:

**wy_dtw <- readNWISdata(stateCd="Wyoming", service="gwlevels")**

only 10,814 measurements populate. I cross checked how many measurements there should be by running the NWIS gwlevels url for WY and there should be 64,386 measurements (url below).

I could be missing something totally obvious and any advice would be so greatly appreciated! 

Thank you very much, 
Lydia
 
(https://nwis.waterdata.usgs.gov/nwis/gwlevels?state_cd=wy&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&format=rdb&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=state_cd)

**Comment by ldecicco-USGS** [comment]
dataRetrieval pulls from the water services site:
https://waterservices.usgs.gov/rest/GW-Levels-Test-Tool.html

This service returns only the most recent data for each site. So, if you add a start and end date, you get all the data:

```
wy2 <- readNWISdata(stateCd = "Wyoming", service = "gwlevels",
                   startDT = "1850-01-01",
                   endDT = "2020-04-23")
nrow(wy2)
[1] 64456
```

**Comment by lydiableifuss** [comment]
Amazing! Thank you so much Laura. This was such a helpful fix and I am sorry to have missed that obvious addition. 

Thanks again for getting back to me so quickly,
Lydia
