### ISSUE TITLE
ResultMeasureValue

### ISSUE THREAD

**Issue by HeatherMM1321** [USGS-R/dataRetrieval#522]
When pulling data from the WQP the ResultMeasureValue is pulled as a numeric value. Unfortunately, some of these values were put in with extra symbols (i.e. <, >). When pulled with the readWQPdata() these values are converted to NA. Is there any way around this? 

```r
library(dataRetrieval)
library(dplyr)

# pulling in data from the Tualatin watershed in Oregon, than filtered by Surface Water samples 
pulled_data <- readWQPdata(statecode="US:41", characteristicName="Escherichia coli", 
                    huc = 17090010,
                    startDateLo = "01-01-2000", 
                    startDateHi = "01-01-2020") %>% 
      filter(ActivityMediaSubdivisionName == "Surface Water") 

# all NA values in the pulled data 
pulled_data[is.na(pulled_data$ResultMeasureValue), ]
```

![image](https://user-images.githubusercontent.com/52505667/92048921-b8f3e100-ed3d-11ea-817c-a0de7795dfdf.png)

readWQPdata() reads all other columns in as characters, this is the only value read in as a numeric. Is there a way to force it to read in the values as a character so that I can clean the data appropriately?

**Comment by ldecicco-USGS** [comment]
Sorry I missed this earlier! 

Not that long ago I did change the import code to not force a numeric:
https://github.com/USGS-R/dataRetrieval/blob/master/R/importWQP.R#L103
But I think in your case, the "<"'s and other text come in after `readr` has already decided on a column type.  I think that number is 10,000 rows or something, but there's some way to make that essentially infinite. 

Thanks for making the issue, I'll try to get that fixed pretty soon, there are a few other small updates we're working on.

**Comment by HeatherMM1321** [comment]
![image](https://user-images.githubusercontent.com/52505667/95662443-d6aa2800-0aeb-11eb-81f6-53ed2d151977.png)

![image](https://user-images.githubusercontent.com/52505667/95662428-c1cd9480-0aeb-11eb-80bd-a43ff3993404.png)

I am newish to this, but would it just be as simple as defining the guess_max as inf?

**Comment by ldecicco-USGS** [comment]
Oh sorry! Yeah, forgot about this. I need to get a few dataRetrieval tasks done, and hoping to knock them all out on Monday.

**Comment by HeatherMM1321** [comment]
Quick question. 

I have updated the package but for some reason my version of the package is missing the ReseultMeasureValue line in importWQP(). The package versions match and only that single line is different. Would you happen to have an idea of why this might be? 

Thank you!

**Comment by ldecicco-USGS** [comment]
OK, try:
```r
remotes::install_github("USGS-R/dataRetrieval")
```
After testing `Inf`, I ran the tests and they were on average 3 times as long to complete. So now, the value comes in by default as a character, and if can convert to a number without any warnings, it'll become a number.
