### ISSUE TITLE
Development Work: NLDI wrapper

### ISSUE THREAD

**Issue by mikejohnson51** [USGS-R/dataRetrieval#523]
Hi @ldecicco-USGS ,

After speaking with @dblodgett-usgs and @jsta , we would like to propose the following wrapper around the NLDI for `dataRetrieval`.

The signature would read:

```r
#' @title Get NLDI Data
#'
#' @description This function acts as a formal query to the NLDI to navigate and find features from a known start point
#' @param comid an NHD COMID value
#' @param nwis  a USGS station ID
#' @param huc12 a HUC12 id 
#' @param wade Water Data Exchange 2.0 Sites
#' @param wqp a water quality portal location ID
#' @param nav where to navigate from the starting point ("UT", "DT", "UM", "DD")
#' @param find what resources to find along the navigation path ("comid", "huc12pp", "npdes_rad", "nwis", "wqp")
#' @param distance_km how far to look along the navigation path in kilometers
#' @return a list of data.frames

findNLDI = function(comid = NULL, nwis = NULL, huc12 = NULL, npdes_rad = NULL, wqp = NULL,
                    nav = NULL, location = NULL, find = NULL, distance_km = NULL){}
```

Where:

***

`comid`, `nwis`, `huc12`, `wade`, `wqp` and `location` are the potential starting points. 

All are given as the identifier in the native data source (e.g. `comid = 101` or `nwis = 11120000`).

`location` would be provided as a lng, lat pair (e.g. `c(-119, 34.6)`). 

**Only one of these is allowed/required**.

***

`nav` defines the direction(s) to search. This can be singular (e.g. `nav = "UT"`) or multiple (e.g. `nav = c("UT", "UM"`)`)

***

`find` describes what features to find on the network and can include any of the starting types (except `location`)

***

`distance_km` controls the search distance in kilometers and terminates network tracing.

***

The return of this function would be a list of `data.frames`, one for all entities requested, including the starting feature, the navigation sets, and the found attributes. 

To avoid an `sf` dependency the results will not be spatial but could quickly be made spatial by any user with `sf::st_as_sf`

***

## **Use case**: 

Find all upstream NWIS site(s) from COMID 101. Here the current implantation returns `sf` objects. _This would be modified for `dataRetreival`_ 

``` r
source('/Users/mikejohnson/Documents/GitHub/HydroData/R/findNLDI.R')
library(sf)
#> Warning: package 'sf' was built under R version 4.0.2
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1

seek = findNLDI(comid = 101, nav = c("UT", "UM"), find = "nwis")

str(seek, max.level = 1)
#> List of 5
#>  $ site    : tibble [1 × 8] (S3: sf/tbl_df/tbl/data.frame)
#>   ..- attr(*, "sf_column")= chr "geometry"
#>   ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
#>   .. ..- attr(*, "names")= chr [1:7] "source" "sourceName" "identifier" "name" ...
#>  $ UT      : tibble [1,815 × 2] (S3: sf/tbl_df/tbl/data.frame)
#>   ..- attr(*, "sf_column")= chr "geometry"
#>   ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA
#>   .. ..- attr(*, "names")= chr "nhdplus_comid"
#>  $ UM      : tibble [14 × 2] (S3: sf/tbl_df/tbl/data.frame)
#>   ..- attr(*, "sf_column")= chr "geometry"
#>   ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA
#>   .. ..- attr(*, "names")= chr "nhdplus_comid"
#>  $ nwissite: tibble [7 × 8] (S3: sf/tbl_df/tbl/data.frame)
#>   ..- attr(*, "sf_column")= chr "geometry"
#>   ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
#>   .. ..- attr(*, "names")= chr [1:7] "source" "sourceName" "identifier" "name" ...
#>  $ NA      : NULL

plot(seek$UT$geometry, col = "blue", lwd = .5)
plot(seek$UM$geometry, col = "red", lwd = 2,add = TRUE)
plot(seek$site$geometry, lwd = 4, col = "purple", add = TRUE)
plot(seek$nwissite$geometry, col = "darkgreen", pch = 16, add = TRUE)
```

![](https://i.imgur.com/Dol2tT6.png)

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

****

Is this of interest, and what changes would you like to see if so,

Thanks!

Mike

PS all the tasks below will be easy to tackle.

New features should include all of the following work:

* [x] Create the function/code 
* [x] Create tests in tests/testthat folder
* [x] Create help file using roxygen2 above code.
* [x] Create working examples in help file (via roxygen2)
* [x] Add to appropriate vignette (or create new one)
* [ ] Add example README
* [x] Check that `devtools::check()` produces no errors, warnings, or notes
* [x] Check that `covr::package_coverage()` has not significantly decreased

Feel free to create independent issues for each of these subtasks. 
This task should not be considered completed until all of the above boxes are checked, or a reasonable argument is made for ignoring a section (ie...not appropriate for top-level README overview).

**Comment by dblodgett-usgs** [comment]
The only change I would suggest is dropping the WaDE, and NPDES inputs. Finding a way to allow specifying those and other NLDI feature sources as a starting points would be nice to have. The list format I use in nhdplusTools might be a way to go in addition to the easier names id inputs?

**Comment by mikejohnson51** [comment]
Hi @dblodgett-usgs, 

So I have been thinking about this some. One nice feature of having all possible feature sources as arguments is that it allow for a consistent pattern of:

```r
findNLDI(start, nav, find)
```

where the `start` is defined by the argument

```r
findNLDI(comid = 101, nav = "UT", find = NULL)
findNLDI(nwis = 11120000, nav = "UT", find = "wqp")
```

what you are saying is instead is something like:

```r
findNLDI(start = c("comid", 101), nav = "UT", find = NULL)
findNLDI(start = c("nwis", 11120000), nav = "UT", find = "wqp")
```

I like that but then all "start" arguments (comid, nwis, wade, wqp, ect) would be dropped correct?

This is nice because it would let the function expand without heavily maintaining the signature and internals

Mike

**Comment by dblodgett-usgs** [comment]
I think having the function signature have a few very-common featureSources as function parameters is good but we also need to allow specification of adhoc / future featureSources. 

So findNLDI would be:

```r
findNLDI <- function(comid = NULL, nwis = NULL, huc12 = NULL, start = NULL, ...)
```

**Comment by mikejohnson51** [comment]
Perfect! I will work on a pull request this week containing this,

```r
#' @title Get NLDI Data
#'
#' @description This function acts as a formal query to the NLDI to navigate and find features from a known start point
#' @param comid an NHD COMID value
#' @param nwis  a USGS station ID
#' @param huc12 a HUC12 id 
#' @param locations and sf POINT object or, lng,lat pair (eg, c(-119,24.5))
#' @param start other starting feature passed as c(type, ID) (eg c("wade, "XXXX"))
#' @param nav where to navigate from the starting point ("UT", "DT", "UM", "DD")
#' @param find what resources to find along the navigation path ("comid", "huc12pp", "npdes_rad", "nwis", "wqp")
#' @param distance_km how far to look along the navigation path in kilometers
#' @return a list of data.frames

findNLDI = function(comid = NULL, nwis = NULL, huc12 = NULL,  location = NULL, start = NULL,
                    nav = NULL,  find = NULL, distance_km = NULL){}
```

**Comment by mikejohnson51** [comment]
@dblodgett-usgs @ldecicco-USGS I have mostly wrapped this up but want to raise one issue about keeping coordinates in the output of this function. Keeping and formatting the `geojson` without a `geojson` parser (new dependency, sf, or a lot of redundant inefficient code :)) is quite tedious and makes the data pretty heavy. It also it a challenge to return something that sf can easily convert to `sf`. Maybe you know of a way I don't?

If not, I am proposing to add a `parser = FUN` argument that can pass a function to the function. We can add a spatial parser in `nhdplusTools` to return sf objects and here simply return the list of identifiers for each request.  

```r
findNLDI = function(comid = NULL, nwis = NULL, huc12 = NULL,  location = NULL, start = NULL,
                    nav = NULL,  find = NULL, distance_km = NULL, parser = FUN){}
```

Does that sound reasonable?

Mike

**Comment by dblodgett-usgs** [comment]
What we really want for dataRetrieval is the NWIS and WQP ID discovery. Given that, all we would ever return to dataRetrieval-only clients would be a table with points. So I think we SHOULD include a parser for point GeoJSON that would return a data.frame with lat and lon columns. In the case of lines and polygons, there should be a way to gracefully check if `sf` is installed with require()? If it's not installed and someone asks for geometry, they should get a warning and only get the IDs back? If it is installed, they just get the `sf` `data.frame`?

NOTE: I goofed above and didn't include WQP in the list I was suggesting be included as named function parameters. It SHOULD be included.

**Comment by mikejohnson51** [comment]
Great, can do. 

So to be clear, if sf **is** installed, points like NWIS and WQP should be returned as (ID, LAT, LNG) `data.frame`s, not  an`sf` object (ID, geometry). 

LINE and POLYGON features will be returned with the `sfc` geometry list column but in `data.frame` form if sf is installed. Otherwise just as a list of IDs

**Comment by dblodgett-usgs** [comment]
My vote would be that if **sf is installed**, you would get a geometry column in addition to the ID, Lat, Lng (for points only). If **sf is not installed**, you just wouldn't get the geometry column.
