### ISSUE TITLE
Help understanding "failed to parse" warning from whatNWISdata

### ISSUE THREAD

**Issue by jennymurphy** [USGS-R/dataRetrieval#565]
Hi! I used the following line of code to retrieve sample information about a particular HUC:

wq1 <- whatNWISdata(huc = "08")

And I got this -->
Warning messages:
1:  40 failed to parse. 
2:  5 failed to parse.

I'm not really sure what these are telling me. Did something "go wrong" during the retrieval? Any insight on these messages? Thanks

**Comment by jennymurphy** [comment]
That makes sense. Thanks so much.

**Comment by jennymurphy** [comment]
That makes sense. Thanks so much!

**Comment by ldecicco-USGS** [comment]
I'm going to leave this open to remind myself of adding the convertType option
