### ISSUE TITLE
What is the short parameter group name for stable isotopes?

### ISSUE THREAD

**Issue by jmusgs** [USGS-R/dataRetrieval#570]
I have a working Shiny app that retrieves data by State and parameter group.  I was recently asked to find data for N15 of NO3, and realized I wasn't getting stable isotopes.  The app uses the short names for parameter groups: readNWISqw {dataRetrieval}, 

Details
Valid parameter code groups are "All," or group codes:
Code    Description
INF    Information
PHY    Physical
INM    Inorganics, Major, Metals (major cations)
INN    Inorganics, Major, Non-metals (major anions)
NUT    Nutrient
MBI    Microbiological
BIO    Biological
IMN    Inorganics, Minor, Non-metals
IMM    Inorganics, Minor, Metals
TOX    Toxicity
OPE    Organics, pesticide
OPC    Organics, PCBs
OOT    Organics, other
RAD    Radiochemical
SED    Sediment
POP    Population/community
 
Although stable isotopes are not listed, they should be "ISO" based on the url such as: https://nwis.waterdata.usgs.gov/nwis/qwdata/?site_no=413144073115701&agency_cd=USGS&param_group=ISO&format=rdb, for example, for nutrients this same related url is:
https://nwis.waterdata.usgs.gov/nwis/qwdata/?site_no=413144073115701&agency_cd=USGS&param_group=NUT&format=rdb.
 
I should be able to get to this with a construction in dataRetrieval like:

library(dataRetrieval)

 

test <- readNWISqw("413144073115701" , "NUT", startDate = "2000-01-01", 
            endDate = "2010-12-31",
            expanded = TRUE, reshape = F, tz = "America/New_York")
above example is for nutrients

**Comment by ldecicco-USGS** [comment]
It appears to be ISO. I'll add that and check to see if more have been added.
