### ISSUE TITLE
Documenting workaround when curl::has_internet returns FALSE

### ISSUE THREAD

**Issue by mps9506** [USGS-R/dataRetrieval#585]
Hi,

I recently started running into an issue with `readWQPdata()` and related returning `No internet connection.`, traced back to: https://github.com/USGS-R/dataRetrieval/blob/b60c41a2b5a36e60a5d08bfeabc974dfc4bf83a0/R/getWebServiceData.R#L25-L28 In my case `curl::has_internet()` returns FALSE even though I had internet access (interestingly, `readWQPdata()` works in a fresh R session, but didn't work in a targets project). 

I have zero understanding of the inner workings of curl or networking, but this is clearly related to some combination of curl and our organization's network configs. This [StackOverflow thread](https://stackoverflow.com/questions/59796178/r-curlhas-internet-false-even-though-there-are-internet-connection) has two possible user solutions. 

I don't think this issue requires changes to the package, but it might be worth documenting the work around somewhere assuming others might run into the problem. Either of the two functions below can be run in the current session so that `curl::has_internet` returns TRUE. Obviously this doesn't work if there is actually isn't internet. 

```r
assign("has_internet_via_proxy", TRUE, environment(curl::has_internet))
```

or 

```r
remove_has_internet <- function()
{
  unlockBinding(sym = "has_internet", asNamespace("curl"))
  assign("has_internet", function() return(TRUE), envir = asNamespace("curl"))
  lockBinding(sym = "has_internet", asNamespace("curl"))
}
remove_has_internet()
```

**Comment by ldecicco-USGS** [comment]
Ug, that sounds frustrating! Looks like you have a workaround for now. I could take this out - if it's a problem with pipelines or other proxy's that's going to be a problem quickly for others. CRAN has some very strict rules on "failing gracefully" if there's no internet, so this was one way that was recommended. I've got other things in place too, so this is redundant.

**Comment by ldecicco-USGS** [comment]
I tried implementing the function...from my understanding, it should be OK. Give it a try:

```r
remotes::install_github("USGS-R/dataRetrieval")
```
If it seems to work for you, let me know and we can close this issue. It will get out on the next round of updates, not sure when that will be.

**Comment by mps9506** [comment]
It works! Thank you for incorporating this!
