### ISSUE TITLE
Why do records retrieved from dataRetrieval differ from those available online at USGS.gov?

### ISSUE THREAD

**Issue by mb451** [USGS-R/dataRetrieval#586]
**What is your question?**
Why do records retrieved from dataRetrieval differ from those available online at USGS.gov?

**To Reproduce**
If possible, narrow down the question to a `dataRetrieval` query:

The following queries produce temperature records 130 rows long spanning 1968-10-04 to 1972-06-15. 

```r
readWQPqw("USGS-03012550", "00010") 
readNWISqw("03012550", "00010") 
```
However, the same query conducted at https://nwis.waterdata.usgs.gov produces a much more recent and longer temperature record. I assume, perhaps incorrectly, that these two data streams should be the same. 

Does anyone have any insight? 

**Session Info**
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

**Comment by ldecicco-USGS** [comment]
The modern temperature data for that site is in the "uv" or "dv" services (meaning, it's from a sensor - the "uv" data is the instantaneous sensor readings, the "dv" is usually daily mean (although I think with temperature they also have daily min/max). You can figure out what service to use like this:

```r
x <- whatNWISdata(siteNumber = "03012550", parameterCd = "00010")
```
Then, to get the data:
```r
dv <- readNWISdv("03012550", parameterCd = "00010")
uv <- readNWISuv("03012550", parameterCd = "00010")
```

The data from the "qw" service or WQP is discrete measurements (so back in the 60s-70s, someone went out there to take a measurement)
