### ISSUE TITLE
IL County Name Incorrect

### ISSUE THREAD

**Issue by nrlottig** [USGS-R/dataRetrieval#608]
**Describe the bug**
DeWitt County (IL) in the CountyCd table is listed as "De Witt County". Data is tagged correctly with DeWitt County.

Verified online that is DeWitt (https://www.dewittcountyill.com/) with no space.

**Comment by nrlottig** [comment]
When pulling data using county the data fails to pull because the lookup table is incorrect.

**Comment by ldecicco-USGS** [comment]
Inspiration to finally get to #564!

**Comment by ldecicco-USGS** [comment]
Should be fixed. Definitely reopen the issue if you notice anything still amiss.
