### ISSUE TITLE
Add convertType to WQP functions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#610]
Just like the NWIS functions, there should be an argument in the WQP functions to bring in everything as character instead of having dataRetrieval try to make the correct dates/numerics/etc.

**Comment by alkrall** [comment]
1) Added: 
```r
convertType=TRUE
```
if statement to `importWQP`.
2) Added convertType to function call in `importWQP`, `readWQPdata`, `readWQPqw`, `whatWQPdata`.
3) Set: 
```r
convertType=convertType 
```
to `importWQP` function call within `readWQPdata`, `readWQPqw`, and `whatWQPdata`. 
4) Added reoxygen documentation to `importWQP`, `readWQPdat`a, `readWQPqw`, `whatWQPdata`.
5) Added tests to testthat.R.
	-Test issues raised in `whatWQPsamples` and `whatWQPmetrics` with `importWQP`.
