### ISSUE TITLE
All requests timing out?

### ISSUE THREAD

**Issue by mspear2** [USGS-R/dataRetrieval#622]
It seems all readNWISdv() requests, even basic ones, are timing out. I had momentary success with the following code, but it seems to only successfully retrieve data one out of every 10 times, timing out in the other attempts.

readNWISdv(siteNumbers = "05533600", 
parameterCd="00060",
 startDate = as.Date('2019-06-01'), 
endDate = as.Date('2019-06-30'))

**Comment by ldecicco-USGS** [comment]
I'm trying to get some details from the NWIS folks! Looks like the "uv" service is still working but pretty much everything else is timing out.

WQP is fine.

**Comment by mspear2** [comment]
I appreciate the quick reply. I'll stay tuned.
________________________________

**Comment by ldecicco-USGS** [comment]
The initial guess is someone's doing a massive parallel processing job and hitting the services like crazy. The server logs right now are off the charts. The dev-ops team is on the case, I'll let you know when I hear anything.

**Comment by joshualerickson** [comment]
Hey @ldecicco-USGS, in response to hitting the servers too frequently, is there a rate limit that dev-ops would like to see for the service, e.g 30/min, 60/min, etc? Working with the [whitewater](https://github.com/joshualerickson/whitewater) package to try and not overload requests and one solution by @HenrikBengtsson was to put a rate limit on the requests, see discussion [here](https://github.com/HenrikBengtsson/future/discussions/630). This would allow the user to still use parallel (future framework) while respecting the server. Thoughts?

**Comment by dblodgett-usgs** [comment]
@jkreft-usgs might want to weigh in here?
