### ISSUE TITLE
startDateLo argument not working for readWQPdata

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/dataRetrieval#64]
> wqp_DF1 <- readWQPdata(statecode="US:20", siteType="Stream", sampleMedia="Water", startDateLo="01-01-2014",characteristicType="Nutrient" )
> min(wqp_DF1$ActivityStartDate)
[1] "1916-06-11"

Seems to be an issue since this last round of commits from earlier this week.

**Comment by lawinslow** [comment]
Hey @eread-usgs, I missed this bit when we were looking at this before. For the `startDateLo`, that date is being interpreted as January 20th, year 1. 

````
as.Date('01-01-2014')
[1] "0001-01-20"
````

The below code works for me now. 
````
wqp_DF1 <- readWQPdata(statecode="US:20", siteType="Stream", sampleMedia="Water", startDateLo="2014-01-01", characteristicType="Nutrient" )
min(wqp_DF1$ActivityStartDate)
[1] "2014-01-13"
````

Argh date functions in R silently failing (shakes fist).

**Comment by ldecicco-USGS** [comment]
That's a bug. The goal of my changes on Friday was that you could import an R date object, *or* the format that WQP wants. Let me see what the problem is and fix it. Sorry for the silent fail...

**Comment by ldecicco-USGS** [comment]
OK dataRetrievialer's let me know if it's fixed for you.
