### ISSUE TITLE
should the more specific functions make use of generics? (e.g, readNWISdata.r)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#71]
Seems that the generic `readNWISdata.r` isn't called by the other functions that take specific args. Could reduce the code to pass the args into the generic function to build the URLs and deal with the responses in one location. Thoughts?

**Comment by jread-usgs** [comment]
For example, 
```R
readNWISdv <- function (siteNumber,parameterCd,startDate="",endDate="",statCd="00003"){  
  
  url <- constructNWISURL(siteNumber,parameterCd,startDate,endDate,"dv",statCd=statCd)

  data <- importWaterML1(url, asDateTime=FALSE)
  if(nrow(data)>0){
    data$dateTime <- as.Date(data$dateTime)
    data$tz_cd <- NULL
    
    names(data)[names(data) == "dateTime"] <- "Date"    
  }
  

  return (data)
}
```
would be
```R
readNWISdv <- function (siteNumber,parameterCd,startDate="",endDate="",statCd="00003"){  
#eating my own dawgfood:
  data <- readNWISdata(site = siteNumber, parameterCd = parameterCd, startDt=startDate, endDt=endDate, statCd="00003")
  return (data)
}

**Comment by ldecicco-USGS** [comment]
Yeah probably a good idea. There wasn't a `readNWISdata` function until just recently (which is the historical reason why they are all constructURL + importWaterML1). The other question then is whether or not to get `readNWISdata` to go to waterservices and waterdata. I see no reason not to, just have to get some time freed up to do it.

**Comment by lawinslow** [comment]
Would this change external functionality or is it just an internal enhancement?

**Comment by ldecicco-USGS** [comment]
No, just internally make the code cleaner.

**Comment by jread-usgs** [comment]
this would not modify the API. But it would result in a more consistent return for data. Would avoid some functions returning "Date" and others "DateTime".

**Comment by lawinslow** [comment]
I thought that the difference in returns was a conscious decisions and not a by-product of design?

**Comment by ldecicco-USGS** [comment]
The Date/DateTime thing was a request from Dave to differenciate when you get back dates vs. posixs'.

**Comment by lawinslow** [comment]
Ah, k. That's what I thought.

**Comment by jread-usgs** [comment]
OK, didn't know that. That's one of the reasons why putting that up as an issue is powerful...I thought that was a bug or a mistake.

**Comment by ldecicco-USGS** [comment]
Yeah, if the reason to change is purely to get a constant output, just use `readNWISdata` from the get-go? The dv/unit/gwl/rating/meas/etc functions are specifically designed to help users get the most useful return for that specific set of data. In my opinion, 'advanced' users would use `readNWISdata`.

**Comment by jread-usgs** [comment]
No, the reason I am suggesting it is to reduce the amount of duplicated code internally. Not necessarily a user need, but a maintenance suggestion.

**Comment by ldecicco-USGS** [comment]
Oh, I agree - I'll put it on the to-do list, unless you feel like doing it an submitting a pull request of course.

**Comment by jread-usgs** [comment]
Yeah, I may self-assign and try my hand.
