### ISSUE TITLE
Unsupported pcodes

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/dataRetrieval#74]
I received an error the other day about "pcodes may be mistyped...". Unfortunately, I did not save the exact error. However, pcodes were retrieved using whatNWISdata so they were not mistyped. I was pulling all data for a site, and the "mistyped" pcodes looked like something from a pesticide schedule. 

I will make sure to save the error next time with exact pcodes.
The code I am using to do this data pull is in the QWToolbox package under the publicData function.

**Comment by tmills-usgs** [comment]
Here is the error:

Error in data[, 1:2] : incorrect number of dimensions
In addition: Warning message:
In readNWISpCode(parameterCd) :
  The following pCodes seem mistyped, and no information was returned: 96151,96750,96759,96764,96765,96767,96775,96777,96778,96802,96812

**Comment by tmills-usgs** [comment]
Here is my code:

STAIDS <- 11264500
parm.group.check <- TRUE
dl.parms  <- "All"

    begin.date <- ""
    end.date <- ""

###Get available data for the site
availableData <- whatNWISdata(STAIDS, service = "qw")

#Subset results to selected parmeters
if (parm.group.check == TRUE) 
{
  if(dl.parms != "All")
  {
    pCodes <- unique(availableData$parm_cd[
      which(availableData$parm_grp_cd == dl.parms)])
  } else{ pCodes <- unique(availableData$parm_cd)} 
} else {pCodes <- unique(availableData$parm_cd[
  which(availableData$parm_cd %in% dl.parms)])}
###
pCodes <- pCodes[which(pCodes != "")]
###Pull data into long data frame
PlotTable <- readNWISqw(STAIDS,pCodes),begin.date,end.date)

**Comment by ldecicco-USGS** [comment]
So actually, what is happening is that more than 200 parameter codes are being requested. NWIS comes back with a 200 status (ie., 'all's good'), but the result is an html message that it's not actually happy. 

I'm just implementing the parameterCd = 'all' option. This should fix the issue. I also check for requests greater than 200 p codes (also fix the issue by giving a useful error message). The fix will be on gitHub today, and submitted to CRAN today as well (probably take a few days to get out to the mirrors).
