### ISSUE TITLE
acceptEncoding=gzip

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#77]

**Comment by ldecicco-USGS** [comment]
@lawinslow, @jiwalker-usgs, or @jread-usgs 
I think this is the default using httr, but I'm still on RCurl. Anyone see an easy way to do in in RCurl?

Here's a comparison:

```r
library(httr)
r <- GET("http://nwis.waterservices.usgs.gov/nwis/iv/?site=05114000&format=waterml,1.1&ParameterCd=00060&startDT=2014-10-10&endDT=2014-10-10")
headers(r)

#vs:

library(RCurl)
h <- basicHeaderGatherer()
r2 <- getURI("http://nwis.waterservices.usgs.gov/nwis/iv/?site=05114000&format=waterml,1.1&ParameterCd=00060&startDT=2014-10-10&endDT=2014-10-10", headerfunction = h$update)
h$value()
```
The headers(r) has"
$`content-encoding`
[1] "gzip"

The h$value() from r2 doesn't say anything about gzip.

**Comment by lawinslow** [comment]
Hmmm. Do you have to specify that you accept gzip in the getURI call? 

```{r}
getURI("http://nwis.waterservices.usgs.gov/nwis/iv/?site=05114000&format=waterml,1.1&ParameterCd=00060&startDT=2014-10-10&endDT=2014-10-10", , httpheader=c('Accept-Encoding'='gzip'), headerfunction = h$update)
````

my initial guess

**Comment by lawinslow** [comment]
```{r}
h$value()
Content-Encoding 
"gzip" 
````

**Comment by ldecicco-USGS** [comment]
You don't get an error with that getURI request?

Error in curlPerform(curl = curl, .opts = opts, .encoding = .encoding) : 
  embedded nul in string: '\037<U+008B>\b'

**Comment by lawinslow** [comment]
Well WTF, worked for me a second ago

**Comment by lawinslow** [comment]
```{r}
getURI("http://nwis.waterservices.usgs.gov/nwis/iv/?site=05114000&format=waterml,1.1&ParameterCd=00060&startDT=2014-11-11&endDT=2014-11-11", httpheader=c('Accept-Encoding'='gzip'), headerfunction = h$update, encoding='gzip')
````

**Comment by lawinslow** [comment]
@ldecicco-USGS Does this work for you now? (also, slack test)

**Comment by ldecicco-USGS** [comment]
Boom. Works. Now I'll see if it helps or not.

**Comment by ldecicco-USGS** [comment]
It seems like you don't need the `httpheader=c('Accept-Encoding'='gzip')`, just:
```r
getURI(url, 
              headerfunction = h$update, 
               encoding='gzip')
```
And it is a tad faster. Nice.
