### ISSUE TITLE
cast and dcast error in importWaterML1

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#80]
```R
Error in dim(ordered) <- ns : 
  dims [product 1] do not match the length of object [0] 
6 cast(data, formula, fun.aggregate, ..., subset = subset, fill = fill, 
    drop = drop, value.var = value.var) 
5 dcast(meltedmergedDF, castFormula, drop = FALSE) 
4 importWaterML1(url, asDateTime = TRUE, tz = tz) 
3 dataRetrieval::readNWISuv(siteNumbers = site, parameterCd = p_code, 
    ...) at get_nwis_df.R#25
```

**Comment by ldecicco-USGS** [comment]
Well that's a new one to me. Got some reproducible code?

**Comment by jread-usgs** [comment]
```R
dataRetrieval::readNWISuv(siteNumbers = "07143672", parameterCd = "00300")
```
fails each time

**Comment by ldecicco-USGS** [comment]
I apparently wrote a comment here but didn't save. Anyway, I can't reproduce the bug. Try installing from gitHub maybe (or, you could do the last tagged release - which should be trickling into a CRAN mirror near you shortly). But, it works just fine for me.

**Comment by lawinslow** [comment]
I couldn't re-create the error.

**Comment by jread-usgs** [comment]
No longer failing, but I didn't update anything. Maybe a quirky nwis thing

**Comment by jread-usgs** [comment]
ok, so the bug only shows up when I specify a startDate:
```R
readNWISuv(siteNumbers = "07143672", parameterCd = "00300", startDate = '2008-01-01')
```
Not sure if it is that start date in particular

**Comment by ldecicco-USGS** [comment]
url is:

http://nwis.waterservices.usgs.gov/nwis/iv/?site=07143672&format=waterml,1.1&ParameterCd=00300&startDT=2008-01-01

**Comment by ldecicco-USGS** [comment]
Problem is here:

<ns1:values><ns1:method methodID="19"><ns1:methodDescription>[Discontinued Oct. 23, 2007]</ns1:methodDescription></ns1:method></ns1:values>

**Comment by jread-usgs** [comment]
looks good to me. works on my examples now.
