### ISSUE TITLE
Did NWIS start blocking multiple rapid requests?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#98]
I am trying to get the state code for a bunch of sites, and am looping through them and using `readNWISsite(nwis_site)`. This has always worked out fine, but now is giving me a bad connection error after a few hundred of them. Seen this before?

**Comment by jread-usgs** [comment]
realized that I can just call `readNWISsite(sites)`, but still curious if this is a thing

**Comment by ldecicco-USGS** [comment]
I had an issue a few weeks back like that too. I emailed NWIS a reproducible example because they didn't want that behavior. I think they thought they fixed it. I'll try it out again and see if the problem has crept back in.
